<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Neuz diwezhañ",
"1" => "Anv ar fichenn",
"2" => "Ment",
"3" => "Seurt",
"4" => "Kemmet a_",
"5" => "Oberiadennoù",
"6" => "Adenvel",
"7" => "Diverkañ",
"8" => "Teuliad",
"9" => "Fichenn MIDI",
"10" => "Diell testenn",
"11" => "Javascript",
"12" => "Skeudenn GIF",
"13" => "Skeudenn JPG",
"14" => "Pajenn HTML",
"15" => "Pajenn HTML",
"16" => "Fichenn REAL",
"17" => "Fichenn REAL",
"18" => "Script PERL",
"19" => "Fichenn ZIP",
"20" => "Son WAV",
"21" => "Script PHP",
"22" => "Script PHP",
"23" => "Fichenn",
"24" => "Teuliad tad",
"25" => "Treuzkas ur fichenn e-barzh : ",
"26" => "Krouiñ un teuliad nevez e-barzh : ",
"27" => "Treuzkas",
"28" => "Krouiñ ur fichenn nevez e-barzh : ",
"29" => "Krouiñ",
"30" => "Roit un anv d'un teuliad he klikit war &quot;Krouiñ&quot;",
"31" => "N'hoc'h eus ket diuzet ur fichenn",
"32" => "War-gil",
"33" => "Mankadenn treuskas !",
"34" => "Ar Fichenn",
"35" => "a zo bet enrollet e-barzh an teuliad",
"36" => "He ment a zo",
"37" => "Ret eo lakaat un anv reizh",
"38" => "An teuliad",
"39" => "a zo bet enrollet e-barzh an teuliad",
"40" => "An teuliad-mañ a zo dija dioutañ",
"41" => "a zo bet adanvet e",
"42" => "e",
"43" => "a zo dija dioutañ(i)",
"44" => "a zo bet diverket",
"45" => "teuliad",
"46" => "fichenn",
"47" => "Ha diverket 'vo da vat a_",
"48" => "YA",
"49" => "NANN",
"50" => "Fichenn EXE",
"51" => "Embann",
"52" => "Embann ar fichenn",
"53" => "Enrollañ",
"54" => "Nullañ",
"55" => "a zo bet kemmet",
"56" => "Skeudenn BMP",
"57" => "Skeudenn PNG",
"58" => "Fichenn CSS",
"59" => "Fichenn MP3",
"60" => "Fichenn RAR",
"61" => "Fichenn GZ",
"62" => "Gwrizhienn al lec'hienn",
"63" => "Dilugañ",
"64" => "Fichenn Excel",
"65" => "Fichenn Word",
"66" => "Eilañ",
"67" => "Fichenn diuzet",
"68" => "Eilañ e-barzh",
"69" => "Pe diuzit un teuliad all",
"70" => "Dilec'hiañ",
"71" => "Ce fichier existe d&eacute;jà",
"72" => "N'eo ket reizh gwrizhienn an teuliad. Gwiriekaat an argemm ar fichenn PRIVE/USERS.TXT",
"73" => "a zo bet eilet en teuliad",
"74" => "a zo bet dilec'hiet en teuliad",
"75" => "N'emañ ket ar fichenn users.txt en teuliad prive",
"76" => "Diverket eo bet ar fichenn-mañ",
"77" => "Kas",
"78" => "Tremen",
"79" => "Fichenn PDF",
"80" => "Fichenn MOV",
"81" => "Fichenn AVI",
"82" => "Fichenn MPG",
"83" => "Fichenn MPEG",
"84" => "Skoazell",
"85" => "Nevesiñ",
"86" => "Serriñ",
"87" => "Klas",
"88" => "Pellgargañ",
"89" => "Dibosupl digeriñ ar fichenn",
"90" => "Moullañ",
"91" => "Fichenn FLASH",
"92" => "Yezh",
"93" => "A-benn dibab ar yezh e rank ho merdeer degemer ar c'houkies.",
"94" => "Login",
"95" => "Dibabit ho yezh :",
"96" => "fichenn",
"97" => "Hollad"
);
?>
