<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "neueste Version",
"1" => "Dateiname",
"2" => "Gr&ouml;sse",
"3" => "Typ",
"4" => "Ge&auml;ndert",
"5" => "Aktionen",
"6" => "umbenennen",
"7" => "l&ouml;schen",
"8" => "Verzeichnis",
"9" => "Midi Datei",
"10" => "Text Datei",
"11" => "Javascript",
"12" => "GIF Bild",
"13" => "JPG Bild",
"14" => "HTML Seite",
"15" => "HTML Seite",
"16" => "REAL Datei",
"17" => "REAL Datei",
"18" => "PERL Script",
"19" => "ZIP Datei",
"20" => "WAV Datei",
"21" => "PHP Script",
"22" => "PHP Script",
"23" => "Datei",
"24" => "Verzeichnis zur&uuml;ck",
"25" => "Eine Datei hochladen ins Verzeichnis : ",
"26" => "Neues Verzeichnis erstellen in : ",
"27" => "hochladen",
"28" => "Neue Datei erstellen in : ",
"29" => "erstellen",
"30" => "Verzeichnisnamen angeben, dann auf &quot;erstellen&quot; klicken",
"31" => "Keine Datei ausgew&auml;hlt",
"32" => "Zur&uuml;ck",
"33" => "Fehler beim Dateitransfer !",
"34" => "Die Datei",
"35" => "wurde erstellt im Verzeichnis",
"36" => "Dateigr&ouml;sse",
"37" => "ung&uml;ltiger Dateiname",
"38" => "Das Verzeichnis",
"39" => "wurde erstellt in",
"40" => "Dieses Verzeichnis ist bereits vorhanden",
"41" => "wurde umbenannt nach",
"42" => "nach",
"43" => "existiert bereits",
"44" => "wurde gel&ouml;scht",
"45" => "Verzeichnis",
"46" => "Datei",
"47" => "Sicher? l&ouml;schen von",
"48" => "JA",
"49" => "NEIN",
"50" => "Exe Datei",
"51" => "Bearbeiten",
"52" => "bearbeite Datei",
"53" => "Speichern",
"54" => "Abbrechen",
"55" => "wurde ge&auml;ndert",
"56" => "BMP Bild",
"57" => "PNG Bild",
"58" => "CSS Datei",
"59" => "MP3 Datei",
"60" => "RAR Datei",
"61" => "GZ Datei",
"62" => "Root Verzeichnis",
"63" => "Beenden",
"64" => "XLS File",
"65" => "Word File",
"66" => "Kopieren",
"67" => "ausgewählte Datei",
"68" => "einfügen in",
"69" => "oder wähle ein anderes Verzeichnis",
"70" => "verschieben",
"71" => "Diese Datei ist bereits vorhanden",
"72" => "Der root Pfad ist nicht richtig. Überprüfe dies in der PRIVE/USERS.TXT Datei",
"73" => "wurde kopiert ins Verzeichnis",
"74" => "wurde verschoben ins Verzeichnis",
"75" => "Die Datei users.txt ist nicht im Verzeichnis prive",
"76" => "Diese Datei wurde verschoben",
"77" => "Senden",
"78" => "Pass",
"79" => "PDF Datei",
"80" => "MOV Datei",
"81" => "AVI Datei",
"82" => "MPG Datei",
"83" => "MPEG Datei",
"84" => "Hilfe",
"85" => "Aktualisieren",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH Datei",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
