<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Viimane versioon",
"1" => "Failinimi",
"2" => "Suurus",
"3" => "T&uuml;&uuml;p",
"4" => "Muudetud",
"5" => "Tegevused",
"6" => "Vaheta nimi",
"7" => "Kustuta",
"8" => "Kaust",
"9" => "Midi fail",
"10" => "Tekstifail",
"11" => "JavaScript",
"12" => "GIF pilt",
"13" => "JPG pilt",
"14" => "HTML leht",
"15" => "HTML leht",
"16" => "REAL-i fail",
"17" => "REAL-i fail",
"18" => "PERL-i skript",
"19" => "ZIP fail",
"20" => "WAV fail",
"21" => "PHP skript",
"22" => "PHP skript",
"23" => "Fail",
"24" => "L&auml;htekaust",
"25" => "Faili &uuml;leslaadimine kausta: ",
"26" => "Loo uus kaust kausta : ",
"27" => "T&otilde;mba &uuml;les",
"28" => "Loo uus fail kausta : ",
"29" => "Loo",
"30" => "Kirjuta kaustale nimi ja seej&auml;rel kl&otilde;psa nupul &quot;Loo&quot;",
"31" => "Sa pead valima faili",
"32" => "Kataloogipuu juurde",
"33" => "Faili &uuml;lest&otilde;mbamisel tekkis viga !",
"34" => "Fail",
"35" => "on edukalt kopeeritud kausta",
"36" => "Selle suurus on",
"37" => "Sa pead kirjutama aksepteeritava nime",
"38" => "Kaust",
"39" => "on loodud kausta",
"40" => "See kaust on juba olemas",
"41" => "nimi on n&uuml;&uuml;dsest",
"42" => "nimeks",
"43" => "juba olemas",
"44" => "on kustutatud",
"45" => "kausta",
"46" => "faili",
"47" => "Kas sa t&otilde;epoolest tahad kustutada",
"48" => "JAH",
"49" => "EI",
"50" => "Exe fail",
"51" => "Toimetamine",
"52" => "Muudan faili",
"53" => "Salvesta",
"54" => "Katkesta",
"55" => "on muudetud",
"56" => "BMP pilt",
"57" => "PNG pilt",
"58" => "CSS Fail",
"59" => "MP3 Fail",
"60" => "RAR Fail",
"61" => "GZ Fail",
"62" => "Juurkataloog",
"63" => "T&ouml;&ouml; l&otilde;pp",
"64" => "XLS File",
"65" => "Word File",
"66" => "Copy",
"67" => "Selected file",
"68" => "Paste in",
"69" => "Or select another directory",
"70" => "Move",
"71" => "See fail on juba olemas",
"72" => "The root path is not correct. Check it in the PRIVE/USERS.TXT file",
"73" => "has been copied into the directory",
"74" => "has been moved into the directory",
"75" => "The file users.txt is not in the directory prive",
"76" => "This file has been removed",
"77" => "Send",
"78" => "Pass",
"79" => "PDF fail",
"80" => "MOV fail",
"81" => "AVI fail",
"82" => "MPG fail",
"83" => "MPEG fail",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH fail",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
