<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Last version",
"1" => "Filename",
"2" => "Size",
"3" => "Type",
"4" => "Modified",
"5" => "Actions",
"6" => "Rename",
"7" => "Delete",
"8" => "Directory",
"9" => "Midi File",
"10" => "Text file",
"11" => "Javascript",
"12" => "GIF picture",
"13" => "JPG picture",
"14" => "HTML page",
"15" => "HTML page",
"16" => "REAL file",
"17" => "REAL file",
"18" => "PERL script",
"19" => "ZIP file",
"20" => "WAV file",
"21" => "PHP script",
"22" => "PHP script",
"23" => "File",
"24" => "Parent directory",
"25" => "Upload a file in the directory : ",
"26" => "Create a new directory in : ",
"27" => "Upload",
"28" => "Create a new file in : ",
"29" => "Create",
"30" => "Write a name for the directory then click on &quot;Create&quot;",
"31" => "You must select a file",
"32" => "Go back",
"33" => "Error uploading file !",
"34" => "The file",
"35" => "has been successfully created in the directory",
"36" => "It's size is",
"37" => "You must write a valid name",
"38" => "The directory",
"39" => "has been create in",
"40" => "This directory already exists",
"41" => "has been renamed to",
"42" => "to",
"43" => "already exists",
"44" => "has been deleted",
"45" => "directory",
"46" => "file",
"47" => "Do you really want to delete the",
"48" => "YES",
"49" => "NO",
"50" => "Exe file",
"51" => "Edit",
"52" => "Editing file",
"53" => "Save",
"54" => "Cancel",
"55" => "has been modified",
"56" => "BMP picture",
"57" => "PNG picture",
"58" => "CSS File",
"59" => "MP3 File",
"60" => "RAR File",
"61" => "GZ File",
"62" => "Root directory",
"63" => "Log out",
"64" => "XLS File",
"65" => "Word File",
"66" => "Copy",
"67" => "Selected file",
"68" => "Paste in",
"69" => "Or select another directory",
"70" => "Move",
"71" => "This file already exists",
"72" => "The root path is not correct. Check it in the PRIVE/USERS.TXT file",
"73" => "has been copied into the directory",
"74" => "has been moved into the directory",
"75" => "The file users.txt is not in the directory prive",
"76" => "This file has been removed",
"77" => "Send",
"78" => "Pass",
"79" => "PDF File",
"80" => "MOV File",
"81" => "AVI File",
"82" => "MPG File",
"83" => "MPEG File",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH File",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :",
"96" => "file",
"97" => "Total"
);
?>
