<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Ultima version",
"1" => "Nombre del fichero",
"2" => "Talla",
"3" => "Tipo",
"4" => "Modificado el",
"5" => "Acciones",
"6" => "Reeligir",
"7" => "Eliminar",
"8" => "Carpeta",
"9" => "Fichero MIDI",
"10" => "Documento texto",
"11" => "Javascript",
"12" => "Imagen GIF",
"13" => "Imagen JPG",
"14" => "Pagina HTML",
"15" => "Pagina HTML",
"16" => "Fichero REAL",
"17" => "Fichero REAL",
"18" => "Script PERL",
"19" => "Fichero ZIP",
"20" => "Sonido WAV",
"21" => "Script PHP",
"22" => "Script PHP",
"23" => "Fichero",
"24" => "Carpeta padres",
"25" => "Enviar un fichero en : ",
"26" => "Crear una nueva carpeta en : ",
"27" => "Enviar",
"28" => "Crear un nuevo fichero en : ",
"29" => "Crear",
"30" => "Tome un nombre de repertorio y haga clic sobre &quot;Crear&quot;",
"31" => "Usted no selecciono el fichero",
"32" => "Vuelta",
"33" => "Error de transferencia !",
"34" => "El fichero",
"35" => "se ha guardado en el repertorio",
"36" => "Su peso es",
"37" => "Deben tomar un nombre de fichero valido",
"38" => "La carpeta",
"39" => "se ha creado en el repertorio",
"40" => "Esta carpeta ya existe",
"41" => "se ha reelegido en",
"42" => "en",
"43" => "ya existe",
"44" => "se ha borrado",
"45" => "repertorio",
"46" => "fichero",
"47" => "Desea usted eliminar definitivamente el",
"48" => "SI",
"49" => "NO",
"50" => "Fichero EXE",
"51" => "Publicar",
"52" => "Publicacion del fichero",
"53" => "Guardar",
"54" => "Cancelar",
"55" => "se ha modificado",
"56" => "Imagen BMP",
"57" => "Imagen PNG",
"58" => "Fichero CSS",
"59" => "Fichero MP3",
"60" => "Fichero RAR",
"61" => "Fichero GZ",
"62" => "Raiz del sitio",
"63" => "desconexiÃ³n",
"64" => "Fichero Excel",
"65" => "Fichero Word",
"66" => "Copiar",
"67" => "Fichero seleccionado",
"68" => "Copiar en",
"69" => "O elige otro repertorio",
"70" => "Desplazar",
"71" => "Este fichero ya existe",
"72" => "La raiz del repertorio es incorrecta. Verificar la variable en el fichero PRIVE/USERS.TXT",
"73" => "se ha copiado en el repertorio",
"74" => "se ha desplazado en el repertorio",
"75" => "El fichero users.txt no esta el repertorio prive",
"76" => "Este fichero se ha eliminado",
"77" => "Enviar",
"78" => "Pase",
"79" => "Fichero PDF",
"80" => "Fichero MOV",
"81" => "Fichero AVI",
"82" => "Fichero MPG",
"83" => "Fichero MPEG",
"84" => "Ayuda",
"85" => "Actualizar",
"86" => "Cerrar",
"87" => "Buscar",
"88" => "Descargar",
"89" => "Imposible de abrir el fichero",
"90" => "Imprimir",
"91" => "Fichero FLASH",
"92" => "Idioma",
"93" => "Para eligir el idioma, su navegador debe aceptar los cookies.",
"94" => "Login",
"95" => "Elija su idioma:",
"96" => "Fichero",
"97" => "Total"
);
 
?>
