<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Dernière version",
"1" => "Nom du fichier",
"2" => "Taille",
"3" => "Type",
"4" => "Modifi&eacute; le",
"5" => "Actions",
"6" => "Renommer",
"7" => "Supprimer",
"8" => "Dossier",
"9" => "Fichier MIDI",
"10" => "Document texte",
"11" => "Javascript",
"12" => "Image GIF",
"13" => "Image JPG",
"14" => "Page HTML",
"15" => "Page HTML",
"16" => "Fichier REAL",
"17" => "Fichier REAL",
"18" => "Script PERL",
"19" => "Fichier ZIP",
"20" => "Son WAV",
"21" => "Script PHP",
"22" => "Script PHP",
"23" => "Fichier",
"24" => "Dossier parent",
"25" => "Transf&eacute;rer un fichier dans : ",
"26" => "Cr&eacute;er un nouveau r&eacute;pertoire dans : ",
"27" => "Transf&eacute;rer",
"28" => "Cr&eacute;er un nouveau fichier dans : ",
"29" => "Cr&eacute;er",
"30" => "Saisissez un nom de r&eacute;pertoire et cliquez sur &quot;Cr&eacute;er&quot;",
"31" => "Vous n'avez pas s&eacute;lectionn&eacute; de fichier",
"32" => "Retour",
"33" => "Erreur de transfert !",
"34" => "Le Fichier",
"35" => "a &eacute;t&eacute; enregistr&eacute; dans le r&eacute;pertoire",
"36" => "Sa taille est de",
"37" => "Vous devez saisir un nom de fichier valide",
"38" => "Le dossier",
"39" => "a &eacute;t&eacute; cr&eacute;&eacute; dans le r&eacute;pertoire",
"40" => "Ce dossier existe d&eacute;jà",
"41" => "a &eacute;t&eacute; renomm&eacute; en",
"42" => "en",
"43" => "existe d&eacute;jà",
"44" => "a &eacute;t&eacute; effac&eacute;",
"45" => "r&eacute;pertoire",
"46" => "fichier",
"47" => "Voulez-vous supprimer d&eacute;finitivement le",
"48" => "OUI",
"49" => "NON",
"50" => "Fichier EXE",
"51" => "Editer",
"52" => "Edition du fichier",
"53" => "Enregistrer",
"54" => "Annuler",
"55" => "a &eacute;t&eacute; modifi&eacute;",
"56" => "Image BMP",
"57" => "Image PNG",
"58" => "Fichier CSS",
"59" => "Fichier MP3",
"60" => "Fichier RAR",
"61" => "Fichier GZ",
"62" => "Racine du site",
"63" => "D&eacute;connexion",
"64" => "Fichier Excel",
"65" => "Fichier Word",
"66" => "Copier",
"67" => "Fichier s&eacute;lectionn&eacute;",
"68" => "Copier dans",
"69" => "Ou choisissez un autre r&eacute;pertoire",
"70" => "D&eacute;placer",
"71" => "Ce fichier existe d&eacute;jà",
"72" => "La racine du r&eacute;pertoire est incorrecte. V&eacute;rifier la variable dans le fichier PRIVE/USERS.TXT",
"73" => "a &eacute;t&eacute; copi&eacute; dans le r&eacute;pertoire",
"74" => "a &eacute;t&eacute; d&eacute;plac&eacute; dans le r&eacute;pertoire",
"75" => "Le fichier users.txt n'est pas dans le r&eacute;pertoire prive",
"76" => "Ce fichier a &eacute;t&eacute; supprim&eacute;",
"77" => "Envoyer",
"78" => "Passe",
"79" => "Fichier PDF",
"80" => "Fichier MOV",
"81" => "Fichier AVI",
"82" => "Fichier MPG",
"83" => "Fichier MPEG",
"84" => "Aide",
"85" => "Actualiser",
"86" => "Fermer",
"87" => "Rechercher",
"88" => "T&eacute;l&eacute;charger",
"89" => "Impossible d'ouvrir le fichier",
"90" => "Imprimer",
"91" => "Fichier FLASH",
"92" => "Langue",
"93" => "Pour s&eacute;lectionner la langue, votre navigateur doit accepter les cookies.",
"94" => "Login",
"95" => "Choisissez votre langue :",
"96" => "fichier",
"97" => "Total"
);
?>
