<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Utolsó verzió",
"1" => "File neve",
"2" => "métret",
"3" => "Típus",
"4" => "Módosítva",
"5" => "Mehet",
"6" => "átnevez",
"7" => "töröl",
"8" => "könyvtár",
"9" => "Midi File",
"10" => "Text file",
"11" => "Javascript",
"12" => "GIF kép",
"13" => "JPG kép",
"14" => "HTML oldal",
"15" => "HTML oldal",
"16" => "REAL file",
"17" => "REAL file",
"18" => "PERL script",
"19" => "ZIP file",
"20" => "WAV file",
"21" => "PHP script",
"22" => "PHP script",
"23" => "File",
"24" => "Parent directory",
"25" => "Filet töltve a mappába : ",
"26" => "Új mappa : ",
"27" => "feltölt",
"28" => "Új file készítés a : ",
"29" => "Létrehoz",
"30" => ";",
"31" => "Fálaszd ki a file-t",
"32" => "Vissza",
"33" => "Feltöltési hiba !",
"34" => "A file",
"35" => "Mappa létrehozva",
"36" => "Méret",
"37" => "Írj valódi nevet",
"38" => "A directory",
"39" => "Létrehozva",
"40" => "Hozzáférés megtagadva",
"41" => "Átnevezésre kerül:",
"42" => "to",
"43" => "Nem hajtható végre",
"44" => "Törölve lett",
"45" => "directory",
"46" => "file",
"47" => "Biztosan törölni akarod?",
"48" => "igen",
"49" => "nem",
"50" => "Exe file",
"51" => "Szerkeszt",
"52" => "mutasd a file-t",
"53" => "ment",
"54" => "Mégse",
"55" => "Módosítva lett",
"56" => "BMP kép",
"57" => "PNG kép",
"58" => "CSS File",
"59" => "MP3 File",
"60" => "RAR File",
"61" => "GZ File",
"62" => "Root directory",
"63" => "Kilép",
"64" => "XLS File",
"65" => "Szó file",
"66" => "Másol",
"67" => "Kijelölt file",
"68" => "Beilleszt",
"69" => "Vagy válasz másik mappát",
"70" => "Mozgat",
"71" => "File nem írható",
"72" => "A root útvonal hibás, ellenõrizd a INDEX.PHP3 file-t",
"73" => "Átmásolva  a kijelölt mappába",
"74" => "Áthelyezve a kijelölt mappába",
"75" => "A users.txt -ben meghatározottak nem megfelelõeke",
"76" => "A file törölve lett",
"77" => "Küld",
"78" => "Jelszó",
"79" => "PDF File",
"80" => "MOV File",
"81" => "AVI File",
"82" => "MPG File",
"83" => "MPEG File",
"84" => "Segítség",
"85" => "Frissítés",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH File",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
