<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Ultima versione",
"1" => "Nome file",
"2" => "Dimensione",
"3" => "Tipo",
"4" => "Modificato",
"5" => "Azioni",
"6" => "Rinomina",
"7" => "Cancella",
"8" => "Directory",
"9" => "Midi File",
"10" => "Text file",
"11" => "Javascript",
"12" => "GIF picture",
"13" => "JPG picture",
"14" => "HTML page",
"15" => "HTML page",
"16" => "REAL file",
"17" => "REAL file",
"18" => "PERL script",
"19" => "ZIP file",
"20" => "WAV file",
"21" => "PHP script",
"22" => "PHP script",
"23" => "File",
"24" => "cartella precedente",
"25" => "Manda un file nella cartella : ",
"26" => "Crea una nuova cartella in : ",
"27" => "Manda",
"28" => "Crea una file cartella in : ",
"29" => "Crea",
"30" => "Scrivi un nome per la nuova cartella e poi clicca su &quot;Crea&quot;",
"31" => "Devi scegliere un file",
"32" => "Torna indietro",
"33" => "Errore nell'invio del file!",
"34" => "Il file",
"35" => "è stato creato nella cartella",
"36" => "La sua dimensione è",
"37" => "YDevi inserire un nome valido",
"38" => "La cartella",
"39" => "è stato creato in",
"40" => "Questa cartella già esiste",
"41" => "è stato rinominato in",
"42" => "in",
"43" => "già esiste",
"44" => "è stato cancellato",
"45" => "la cartella",
"46" => "il file",
"47" => "Vuoi davvero cancellare ",
"48" => "SI",
"49" => "NO",
"50" => "Exe file",
"51" => "Modifica",
"52" => "Modifica file",
"53" => "Salva",
"54" => "Cancella",
"55" => "è stato modificato",
"56" => "BMP picture",
"57" => "PNG picture",
"58" => "CSS File",
"59" => "MP3 File",
"60" => "RAR File",
"61" => "GZ File",
"62" => "cartella indice",
"63" => "Disconnessione",
"64" => "Excel File",
"65" => "Word File",
"66" => "Copy",
"67" => "Selected file",
"68" => "Paste in",
"69" => "Or select another directory",
"70" => "Move",
"71" => "Questa file già esiste",
"72" => "The root path is not correct. Check it in the PRIVE/USERS.TXT file",
"73" => "has been copied into the directory",
"74" => "has been moved into the directory",
"75" => "The file users.txt is not in the directory prive",
"76" => "This file has been removed",
"77" => "Send",
"78" => "Pass",
"79" => "PDF File",
"80" => "MOV File",
"81" => "AVI File",
"82" => "MPG File",
"83" => "MPEG File",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH File",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
