<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Paskutinë versija",
"1" => "Failas",
"2" => "Dydis",
"3" => "Tipas",
"4" => "Redaguota",
"5" => "Veiksmas",
"6" => "Pervadinti",
"7" => "Trinti",
"8" => "Katalogas",
"9" => "Midi",
"10" => "Txt",
"11" => "Javascript",
"12" => "GIF",
"13" => "JPG",
"14" => "HTML",
"15" => "HTML",
"16" => "REAL",
"17" => "REAL",
"18" => "PERL",
"19" => "ZIP",
"20" => "WAV",
"21" => "PHP",
"22" => "PHP",
"23" => "Failas",
"24" => "Pagrindinis katalogas",
"25" => "Atsiøsti failus : ",
"26" => "Naujas katalogas : ",
"27" => "Nusiøsti",
"28" => "Sukurti nauja faila : ",
"29" => "Sukurti",
"30" => "Iraðykite katalogo pavadinimà ir spauskite &quot;Sukurti&quot;",
"31" => "Paþymekite failà",
"32" => "Atgal",
"33" => "Klaida atsiunèiant failà !",
"34" => "Failas",
"35" => "katalogas sukurtas sëkmingai",
"36" => "Jo dydis yra",
"37" => "Áveskite teisingà vardà",
"38" => "Katalogas",
"39" => "sukurtas kataloge",
"40" => "Ðis vardas jau egzistuoja",
"41" => "buvo pervadintas á",
"42" => "á",
"43" => "jau egsituoja",
"44" => "buvo iðtrintas",
"45" => "katalogas",
"46" => "failas",
"47" => "Ar tikrai norite iðtrinti",
"48" => "TAIP",
"49" => "NE",
"50" => "Exe",
"51" => "Redaguoti",
"52" => "Failo redagavimas",
"53" => "Iðsaugoti",
"54" => "Atðaukti",
"55" => "buvo redaguotas",
"56" => "BMP",
"57" => "PNG",
"58" => "CSS",
"59" => "MP3",
"60" => "RAR",
"61" => "GZ",
"62" => "Pagrindinis katalogas",
"63" => "Atsijungti",
"64" => "XLS",
"65" => "Word",
"66" => "Kopijuoti",
"67" => "Paþymeti failà",
"68" => "Padëti á",
"69" => "Arba pasirinkite kità katalogà",
"70" => "Perkelti",
"71" => "Ðis failas jau egzistuoja",
"72" => "neteisinnas katalogas",
"73" => "buvo perkopijuotas á katalogà",
"74" => "buvo perkeltas i katalogà",
"75" => "Failas neleistiname kataloge",
"76" => "Failas buvo iðtrintas",
"77" => "Send",
"78" => "Pass",
"79" => "PDF",
"80" => "MOV",
"81" => "AVI",
"82" => "MPG",
"83" => "MPEG",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
