<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Najnowsza wersja",
"1" => "Nazwa pliku",
"2" => "Waga",
"3" => "Typ",
"4" => "Zmodyfikowany",
"5" => "Akcja",
"6" => "Zmien nazwe",
"7" => "Usun",
"8" => "Folder",
"9" => "Plik Midi",
"10" => "Plik textowy",
"11" => "JavaScript",
"12" => "Obraz GIF",
"13" => "Obraz JPG",
"14" => "Strona HTML",
"15" => "Strona HTML",
"16" => "REAL file",
"17" => "REAL file",
"18" => "Skrypt PERL",
"19" => "Plik ZIP",
"20" => "Plik WAV",
"21" => "Skrypt PHP",
"22" => "Skrypt PHP",
"23" => "Plik",
"24" => "W góre",
"25" => "Wyslij plik do folderu : ",
"26" => "Utwórz nowy folder w : ",
"27" => "Wyslij",
"28" => "Utwórz nowy plik w : ",
"29" => "Utwórz",
"30" => "Wpisz nazwe folderu i kliknij na &quot;Utwórz&quot;",
"31" => "Musisz wybrac plik",
"32" => "Powrót",
"33" => "Blad przy wysylaniu !",
"34" => "Plik",
"35" => "zostal poprawnie utworzony w folderze",
"36" => "Rozmiar",
"37" => "Musisz wpisac poprawna nazwe",
"38" => "Folder",
"39" => "zostal utworzony w",
"40" => "Ten folder juz istnieje",
"41" => "nazwa zostala zmieniona na",
"42" => "na",
"43" => "juz istnieje",
"44" => "zostal usuniety",
"45" => "folder",
"46" => "plik",
"47" => "Czy chcesz usunac",
"48" => "TAK",
"49" => "NIE",
"50" => "Plik exe",
"51" => "Edytuj",
"52" => "Edytuj plik",
"53" => "Zapisz",
"54" => "Anuluj",
"55" => "zostal zmieniony",
"56" => "Obraz BMP",
"57" => "Obraz PNG",
"58" => "Plik CSS",
"59" => "Plik MP3",
"60" => "Plik RAR",
"61" => "Plik GZ",
"62" => "Root directory",
"63" => "Log out",
"64" => "Plik XLS",
"65" => "plik DOC"	,
"66" => "Copy",
"67" => "Selected file",
"68" => "Paste in",
"69" => "Or select another directory",
"70" => "Move",
"71" => "Ten gore juz istnieje",
"72" => "The root path is not correct. Check it in the PRIVE/USERS.TXT file",
"73" => "has been copied into the directory",
"74" => "has been moved into the directory",
"75" => "The file users.txt is not in the directory prive",
"76" => "This file has been removed",
"77" => "Send",
"78" => "Pass",
"79" => "Plik PDF",
"80" => "Plik MOV",
"81" => "Plik AVI",
"82" => "Plik MPG",
"83" => "Plik MPEG",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "Plik FLASH",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
