<?php
//---------------------------------------------------------------------------------------------------
//							
//	WebJeff - FileManager v1.6
//	
//	Jean-François GAZET
//	http://www.webjeff.org
//	webmaster@webjeff.org	
//
//---------------------------------------------------------------------------------------------------

$mess=array(
"0" => "Posledná verzia",
"1" => "Súbor",
"2" => "Ve¾kos",
"3" => "Typ",
"4" => "Dátum",
"5" => "Akcia",
"6" => "Premenuj",
"7" => "Zma",
"8" => "Adresár",
"9" => "Midi súbor",
"10" => "Textový súbor",
"11" => "Javascript",
"12" => "GIF obrázok",
"13" => "JPG obrázok",
"14" => "HTML stránka",
"15" => "HTML obrázok",
"16" => "REAL obrázok",
"17" => "REAL súbor",
"18" => "PERL script",
"19" => "ZIP súbor",
"20" => "WAV súbor",
"21" => "PHP script",
"22" => "PHP script",
"23" => "Súbor",
"24" => "Nadradený adresár",
"25" => "Pridaj súbor do adresára: ",
"26" => "Vytvor nový adresár v: ",
"27" => "Pridaj",
"28" => "Vytvor nový súbor v: ",
"29" => "Vytvor",
"30" => "Zapí meno adresára a stlaè &quot;Vytvor&quot;",
"31" => "Musíte vybra súbor",
"32" => "Spä",
"33" => "Chyba pri pridávaní súboru!",
"34" => "Súbor",
"35" => "bol úspene vytvorený v adresári",
"36" => "Ve¾kos je",
"37" => "Musíte potvrdi meno",
"38" => "Adresár",
"39" => "bol vytvorený",
"40" => "Tento adresár u existuje",
"41" => "bol premenovaný na",
"42" => "na",
"43" => "stále existuje",
"44" => "bol zmazaný",
"45" => "adresár",
"46" => "súbor",
"47" => "Chcete naozaj zmaza",
"48" => "ÁNO",
"49" => "NIE",
"50" => "Exe súbor",
"51" => "Edit",
"52" => "Edituj súbor",
"53" => "Ulo",
"54" => "Zru",
"55" => "bol zmenený",
"56" => "BMP obrázok",
"57" => "PNG obrázok",
"58" => "CSS súbor",
"59" => "MP3 súbor",
"60" => "RAR súbor",
"61" => "GZ súbor",
"62" => "Root directory",
"63" => "Log out",
"64" => "XLS súbor",
"65" => "DOC súbor",
"66" => "Copy",
"67" => "Selected file",
"68" => "Paste in",
"69" => "Or select another directory",
"70" => "Move",
"71" => "Tento súbor u existuje",
"72" => "The root path is not correct. Check it in the PRIVE/USERS.TXT file",
"73" => "has been copied into the directory",
"74" => "has been moved into the directory",
"75" => "The file users.txt is not in the directory prive",
"76" => "This file has been removed",
"77" => "Send",
"78" => "Pass",
"79" => "PDF Súbor",
"80" => "MOV Súbor",
"81" => "AVI Súbor",
"82" => "MPG Súbor",
"83" => "MPEG Súbor",
"84" => "Help",
"85" => "Refresh",
"86" => "Close",
"87" => "Search",
"88" => "Download",
"89" => "Unable to open file",
"90" => "Print",
"91" => "FLASH Súbor",
"92" => "Language",
"93" => "To choose your language, your browser must accept cookies.",
"94" => "Login",
"95" => "Select your language :"
);
?>
