ALTER TABLE `T_MSG_MESSAGE` CHANGE `MSG_LIBELLE` `MSG_TEXT` TEXT NOT NULL ;
ALTER TABLE `T_MSG_MESSAGE` ADD `MSG_CR` CHAR(2) NOT NULL AFTER `MSG_TEXT` ;

ALTER TABLE `T_CNT_CONTACT` CHANGE `CNT_PSEUDO` `CNT_NEW_USERNAME` varchar(20) NOT NULL COMMENT='Nickname changed' ;
ALTER TABLE `T_CNT_CONTACT` CHANGE `CNT_PRIVILEGE` `CNT_STATUS` tinyint(4) NOT NULL COMMENT='VIP/hidden' ;
ALTER TABLE `T_CNT_CONTACT` CHANGE `CNT_GROUPE` `CNT_USER_GROUP` varchar(20) NOT NULL ;

ALTER TABLE `T_USR_USER` CHANGE `USR_AUTORIS` `USR_STATUS` tinyint(4) NOT NULL ;
ALTER TABLE `T_USR_USER` CHANGE `USR_NOM` `USR_NAME` VARCHAR(50) NOT NULL COMMENT='Name or function' ;
ALTER TABLE `T_USR_USER` CHANGE `USR_PASSWORD` `USR_PASSWORD` VARCHAR(40) NOT NULL ;
ALTER TABLE `T_USR_USER` ADD `USR_IP_ADDRESS` VARCHAR(23) NOT NULL AFTER `USR_LANGUAGE_CODE` ;
ALTER TABLE `T_USR_USER` ADD `USR_OS` VARCHAR(5) NOT NULL COMMENT='Operating System' ;
ALTER TABLE `T_USR_USER` ADD `USR_EMAIL` VARCHAR(80) NOT NULL ,
ALTER TABLE `T_USR_USER` ADD `USR_PHONE` VARCHAR(20) NOT NULL ;
ALTER TABLE `T_USR_USER` ADD `USR_PWD_ERRORS` SMALLINT NOT NULL COMMENT='Password errors counter' ;
ALTER TABLE `T_USR_USER` ADD `USR_PHONE` VARCHAR(20) NOT NULL ;
ALTER TABLE `T_USR_USER` ADD `USR_GENDER` CHAR(1) NOT NULL COMMENT='Sex' ;

ALTER TABLE `T_SES_SESSION` CHANGE `SES_IP_ADRESS` `SES_IP_ADDRESS` VARCHAR(23) NOT NULL ;
ALTER TABLE `T_SES_SESSION` CHANGE `ETA_NUM` `SES_STATUS` tinyint(4) NOT NULL ;
