  CREATE TABLE IF NOT EXISTS `IM_BAN_BANNED` (
    `BAN_TYPE` char(1) NOT NULL,
    `BAN_VALUE` varchar(50) default NULL,
    INDEX (`BAN_TYPE`, `BAN_VALUE`)
  );


ALTER TABLE `IM_USR_USER` ADD `USR_GET_OFFLINE_MSG` tinyint(4) NOT NULL default '2';
ALTER TABLE `IM_USR_USER` ADD `USR_MAC_ADR` CHAR(12) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_COMPUTERNAME` VARCHAR(20) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_SCREEN_SIZE` VARCHAR(10) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_EMAIL_CLIENT` VARCHAR(40) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_BROWSER` VARCHAR(40) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_OOO` VARCHAR(5) NOT NULL default '';
ALTER TABLE `IM_USR_USER` ADD `USR_RATING` tinyint(4) NOT NULL default '0';
ALTER TABLE `IM_USR_USER` ADD `USR_ONLINE` tinyint(4) NOT NULL default '0';
ALTER TABLE `IM_USR_USER` ADD `USR_TIME_LOCK` TIME NOT NULL default '00:00:00';
ALTER TABLE `IM_USR_USER` ADD `USR_REG` VARCHAR(30) NOT NULL default '';

ALTER TABLE `IM_CNT_CONTACT` ADD `CNT_RATING` tinyint(4) NOT NULL default '0';
