CREATE TABLE IF NOT EXISTS `IM_BMC_BOOKMCATEG` (
  `ID_BOOKMCATEG` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `BMC_TITLE` varchar(80) NOT NULL,
  PRIMARY KEY  (`ID_BOOKMARK`)
) COMMENT = 'Bookmarks';

News - Sport - Entertainemnt - Finance


CREATE TABLE IF NOT EXISTS `IM_BMK_BOOKMARK` (
  `ID_BOOKMARK` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_BOOKMCATEG` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ID_USER_AUT` MEDIUMINT NOT NULL,
  `BMK_URL` varchar(250) NOT NULL,
  `BMK_TITLE` varchar(80) NOT NULL,
  `BMK_DATE` date NOT NULL,
  `BMK_DISPLAY` TINYINT NOT NULL default '1',
  `BMK_RATING` TINYINT NOT NULL default '0',
  PRIMARY KEY  (`ID_BOOKMARK`),
  UNIQUE KEY `BMK_URL` (`BMK_URL`),
  UNIQUE KEY `BMK_TITRE` (`BMK_TITRE`)
) COMMENT = 'Bookmarks';


CREATE TABLE IF NOT EXISTS `IM_BMV_BOOKMVOTE` (
  `ID_BOOKMARK` SMALLINT UNSIGNED NOT NULL,
  `ID_USER_VOTE` MEDIUMINT NOT NULL,
  `ID_USER_AUT` MEDIUMINT NOT NULL COMMENT 'For stats',
  `BMV_DATE` date NOT NULL,
  `BMV_VOTE_M` TINYINT NOT NULL COMMENT 'More',
  `BMV_VOTE_L` TINYINT NOT NULL COMMENT 'Less',
  PRIMARY KEY  (`ID_BOOKMARK`, `ID_USER_VOTE`),
  KEY `BMV_IND_1` (`ID_USER_AUT`)
) COMMENT = 'Votes Bookmarks';
