
CREATE TABLE `T_STA_STATS` (
`STA_DATE` DATE NOT NULL ,
`STA_NB_MSG` INT NOT NULL default '0',
`STA_NB_CREAT` INT NOT NULL default '0',
`STA_NB_SESSION` INT NOT NULL default '0',
PRIMARY KEY ( `STA_DATE` )
) COMMENT = 'Statistics';