INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_OTHER) VALUES (19, 'ALLOW_HIDDEN_STATUS', '');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_ROLE) VALUES (105, 'ROLE_OFFLINE_MODE', 'R');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_ROLE) VALUES (106, 'ROLE_CHANGE_SERVER_STATUS', 'R');

INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (73, 'BACKUP_FILES', 0, 'X');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (74, 'BACKUP_FILES_ALLOW_MULTI_FOLDERS', 0, '');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (75, 'BACKUP_FILES_ALLOW_SUB_FOLDERS', 0, '');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (76, 'BACKUP_FILES_MAX_ARCHIVE_SIZE', 999999, '');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (77, 'BACKUP_FILES_MAX_NB_ARCHIVES_USER', 9, '');
INSERT INTO IM_MDL_MODULE (ID_MODULE, MDL_NAME, MDL_MAX_VALUE, MDL_OTHER) VALUES (78, 'BACKUP_FILES_MAX_SPACE_SIZE_USER', 999999,'');


UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_HIDDEN_TO_CONTACTS' WHERE ID_MODULE = 7 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_CONTACT_RATING' WHERE ID_MODULE = 11 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_HISTORY_MESSAGES' WHERE ID_MODULE = 12 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'HISTORY_MESSAGES_ON_ACP' WHERE ID_MODULE = 14 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_MANAGE_CONTACT_LIST' WHERE ID_MODULE = 30 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_MANAGE_OPTIONS' WHERE ID_MODULE = 31 limit 1;
UPDATE IM_MDL_MODULE SET MDL_NAME = 'ALLOW_MANAGE_PROFILE' WHERE ID_MODULE = 32 limit 1;

UPDATE IM_MDL_MODULE SET ID_MODULE = 59  WHERE MDL_NAME = 'ALLOW_SKIN' and ID_MODULE = 79 limit 1;
UPDATE IM_RLM_ROLEMODULE SET ID_MODULE = 59  WHERE ID_MODULE = 79;


ALTER TABLE IM_USR_USER ADD USR_PASS_WEB varchar(40) NOT NULL default '' AFTER USR_PASSWORD;
ALTER TABLE IM_USR_USER ADD USR_PASS_SALT char(20) NOT NULL default '' AFTER USR_PASS_WEB;
ALTER TABLE IM_USR_USER ADD USR_DATE_BACKUP date NOT NULL default '0000-00-00'  AFTER USR_GET_OFFLINE_MSG;


CREATE TABLE IF NOT EXISTS IM_ADM_ADMINACP (
  ID_ADMIN TINYINT UNSIGNED NOT NULL auto_increment,
  ADM_USERNAME varchar(20) NOT NULL default '',
  ADM_PASSWORD varchar(40) NOT NULL default '',
  ADM_SALT char(20) NOT NULL default '',
  ADM_LEVEL INT UNSIGNED NOT NULL,
  ADM_DATE_CREAT date NOT NULL default '0000-00-00',
  ADM_DATE_LAST date NOT NULL default '0000-00-00',
  ADM_DATE_PASSWORD date NOT NULL default '0000-00-00',
  PRIMARY KEY  (ID_ADMIN)
) COMMENT = 'ACP Admins';





CREATE TABLE IF NOT EXISTS IM_FIB_FILEBACKUP (
  ID_FILEBACKUP INT UNSIGNED NOT NULL auto_increment,
  FIB_NAME VARCHAR(20) NOT NULL,
  ID_USER MEDIUMINT UNSIGNED NOT NULL,
  FIB_ONLINE CHAR(1) NOT NULL,  
  FIB_DATE_ADD date NOT NULL default '0000-00-00',
  FIB_SIZE INT UNSIGNED NULL,
  FIB_HASH CHAR(32) NOT NULL,
  FIB_PROTECT VARCHAR(32) NOT NULL,
  PRIMARY KEY  (ID_FILEBACKUP),
  KEY FIB_IND_1 (ID_USER, FIB_ONLINE, FIB_NAME)
) COMMENT = 'Backup Files';
