ALTER TABLE IM_STA_STATS ADD STA_SF_NB_DOWNLOAD MEDIUMINT UNSIGNED NOT NULL default '0';



ALTER TABLE IM_FIL_FILE ADD FIL_PROTECT VARCHAR(32) NOT NULL AFTER FIL_HASH;
ALTER TABLE IM_FIL_FILE ADD FIL_PASSWORD VARCHAR(32) NOT NULL AFTER FIL_PROTECT;
ALTER TABLE IM_FIL_FILE ADD FIL_COMPRESS CHAR(1) NOT NULL AFTER FIL_PASSWORD;


CREATE TABLE IF NOT EXISTS IM_FSD_FILESTATSDOWNLOAD (
  ID_USER_DL MEDIUMINT NOT NULL,
  ID_FILE_LAST_DL MEDIUMINT UNSIGNED NOT NULL,
  FSD_NB_DOWNLOAD SMALLINT UNSIGNED NOT NULL default '0',
  FSD_LAST_DATE date NOT NULL,
  FSD_NB_LAST_DATE SMALLINT UNSIGNED NOT NULL default '0' COMMENT 'Day quota',
  FSD_TRAFFIC_LAST_DATE MEDIUMINT UNSIGNED NOT NULL default '0',
  FSD_LAST_WEEK TINYINT UNSIGNED NOT NULL default '0',
  FSD_NB_LAST_WEEK SMALLINT UNSIGNED NOT NULL default '0' COMMENT 'Week quota',
  FSD_TRAFFIC_LAST_WEEK INT UNSIGNED NOT NULL default '0',
  FSD_LAST_MONTH TINYINT UNSIGNED NOT NULL default '0',
  FSD_NB_LAST_MONTH SMALLINT UNSIGNED NOT NULL default '0' COMMENT 'Month quota',
  FSD_TRAFFIC_LAST_MONTH INT UNSIGNED NOT NULL default '0',
  PRIMARY KEY  (ID_USER_DL)
) COMMENT = 'Stats download files';
