ALTER TABLE `T_USR_USER` ADD `USR_NB_CONNECT` SMALLINT NOT NULL default '0';
ALTER TABLE `T_USR_USER` ADD `USR_GET_ADMIN_ALERT` tinyint(4) NOT NULL default '0',

ALTER TABLE `T_SES_SESSION` ADD `SES_AWAY_REASON` tinyint(4) NOT NULL default '0';

