ALTER TABLE `IM_MDL_MODULE` ADD `MDL_MAX_VALUE` SMALLINT UNSIGNED NOT NULL default 0;

ALTER TABLE `IM_MDL_MODULE` ADD `MDL_OTHER` CHAR(1) NOT NULL default '';

ALTER TABLE `IM_MDL_MODULE` ADD `MDL_ROLE` CHAR(1) NOT NULL default '';