ALTER TABLE `IM_USR_USER` ADD `USR_DATE_PASSWORD` date NOT NULL default '0000-00-00' AFTER `USR_DATE_LAST`;
ALTER TABLE `IM_USR_USER` ADD `USR_DATE_ACTIVITY` date NOT NULL default '0000-00-00' AFTER `USR_DATE_LAST`;

ALTER TABLE `IM_STA_STATS` ADD `STA_SBX_NB_MSG` MEDIUMINT UNSIGNED NOT NULL default '0';
ALTER TABLE `IM_GRP_GROUP` ADD `GRP_SHOUTBOX` TINYINT NOT NULL DEFAULT '0';
ALTER TABLE `IM_GRP_GROUP` ADD `GRP_SBX_NEED_APPROVAL` TINYINT NOT NULL DEFAULT '0';

ALTER TABLE `IM_STA_STATS` CHANGE `STA_NB_MSG` `STA_NB_MSG` MEDIUMINT UNSIGNED NOT NULL default '0';
ALTER TABLE `IM_STA_STATS` CHANGE `STA_NB_CREAT` `STA_NB_CREAT` SMALLINT UNSIGNED NOT NULL default '0';
ALTER TABLE `IM_STA_STATS` CHANGE `STA_NB_SESSION` `STA_NB_SESSION` SMALLINT UNSIGNED NOT NULL default '0';
ALTER TABLE `IM_STA_STATS` CHANGE `STA_NB_USR` `STA_NB_USR` MEDIUMINT UNSIGNED NOT NULL default '0';

ALTER TABLE `IM_USG_USERGRP` ADD `USG_PENDING` TINYINT NOT NULL DEFAULT '0';

ALTER TABLE `IM_CNT_CONTACT` ADD  `CNT_SOUND` TINYINT UNSIGNED NOT NULL default '0';
