ALTER TABLE `IM_MDL_MODULE` CHANGE `MDL_MAX_VALUE` `MDL_MAX_VALUE` SMALLINT UNSIGNED NOT NULL default 0;

ALTER TABLE `IM_MDL_MODULE` CHANGE `MDL_OTHER` `MDL_OTHER` CHAR(1) NOT NULL default '';

ALTER TABLE `IM_MDL_MODULE` CHANGE `MDL_ROLE` `MDL_ROLE` CHAR(1) NOT NULL default '';
