DROP TABLE `T_GRP_GROUPE`;

CREATE TABLE `T_GRP_GROUP` (
`ID_GROUP` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`GRP_NAME` VARCHAR( 20 ) NOT NULL ,
`GRP_PRIVATE` TINYINT NOT NULL DEFAULT '0',
UNIQUE (`GRP_NAME`)
) COMMENT = 'Group list';




DROP TABLE `T_USG_USERGRP`;

CREATE TABLE `T_USG_USERGRP` (
`ID_GROUP` INT NOT NULL ,
`ID_USER` INT NOT NULL ,
INDEX ( `ID_GROUP` , `ID_USER` )
) COMMENT = 'Users in groups';