<?php
/*******************************************************
 **                  IntraMessenger - server          **
 **                                                   **
 **  Copyright:      (C) 2006 - 2009 THeUDS           **
 **  Web:            http://www.theuds.com            **
 **                  http://www.intramessenger.net    **
 **  Licence :       GPL (GNU Public License)         **
 **  http://opensource.org/licenses/gpl-license.php   **
 *******************************************************/

/*******************************************************
 **       This file is part of IntraMessenger-server  **
 **                                                   **
 **  IntraMessenger is a free software.               **
 **  IntraMessenger is distributed in the hope that   **
 **  it will be useful, but WITHOUT ANY WARRANTY.     **
 *******************************************************/


## (EN) DO NOT EDIT THIS FILE !

## (FR) NE PAS MODIFIER CE FICHIER !


if ( !defined('INTRAMESSENGER') )
{
  exit;
}


$keya = "24fb847bc0a0563892e76664d50fc66d";
$keyb = "DCb6R88AiPiHkotekGuxXZ3bGw";
$keyc = "f18zI22aNVC6kVyjlUj90mI8NoqVEDUNBVVKhrkYyxndnIbu6Q";
$keyd = "69BKf/XASSUpz6s5clRUxE2tidr6tdJhO06uHv2JPGQ";
$keye = "";


?>
