<?php
/*******************************************************
 **                  IntraMessenger - server          **
 **                                                   **
 **  Copyright:      (C) 2006 - 2015 THeUDS           **
 **  Web:            http://www.theuds.com            **
 **                  http://www.intramessenger.net    **
 **  Licence :       GPL (GNU Public License)         **
 **  http://opensource.org/licenses/gpl-license.php   **
 *******************************************************/

/*******************************************************
 **       This file is part of IntraMessenger-server  **
 **                                                   **
 **  IntraMessenger is a free software.               **
 **  IntraMessenger is distributed in the hope that   **
 **  it will be useful, but WITHOUT ANY WARRANTY.     **
 *******************************************************/
//
error_reporting(E_ALL);
//
define('INTRAMESSENGER',true);
$nb_corrections = 0;
$options_fixed = "";
$ready_for_register_on_server_list = "";
if (isset($_POST['lang'])) $lang = $_POST['lang']; else $lang = "";
if (isset($_POST['check'])) $check = $_POST['check']; else $check = "";
//
// install :
if (isset($_POST['step'])) $step = intval($_POST['step']); else $step = 0;
if (isset($_POST['lic'])) $lic = $_POST['lic']; else $lic = "";
//
$checkoptionsonly = "";
if (isset($_POST['submit']))
{
  $submit_array = array_keys($_POST['submit']);
  if ($submit_array[0] == "checkoptions") $checkoptionsonly = "X";
}
//
$repertoire  = getcwd() . "/"; 
if ( (substr_count($repertoire, "/admin_demo/") == 0) and (substr_count($repertoire, "\admin_demo/") == 0) ) 
{
  require ("../common/constant.inc.php");
  require ("../common/functions.inc.php"); // pour les problèmes de dates
  //
  if (isset($_POST['T_MAINTENANCE_MODE'])) $MAINTENANCE_MODE = $_POST['T_MAINTENANCE_MODE']; else $MAINTENANCE_MODE = "";
  if (isset($_POST['T_FLAG_COUNTRY_FROM_IP'])) $FLAG_COUNTRY_FROM_IP = $_POST['T_FLAG_COUNTRY_FROM_IP']; else $FLAG_COUNTRY_FROM_IP = "";
  if (isset($_POST['T_FORCE_USERNAME_TO_PC_SESSION_NAME'])) $FORCE_USERNAME_TO_PC_SESSION_NAME = $_POST['T_FORCE_USERNAME_TO_PC_SESSION_NAME']; else $FORCE_USERNAME_TO_PC_SESSION_NAME = "";
  if (isset($_POST['T_ALLOW_HIDDEN_TO_CONTACTS'])) $ALLOW_HIDDEN_TO_CONTACTS = $_POST['T_ALLOW_HIDDEN_TO_CONTACTS']; else $ALLOW_HIDDEN_TO_CONTACTS = "";
  if (isset($_POST['T_ALLOW_CONFERENCE'])) $ALLOW_CONFERENCE = $_POST['T_ALLOW_CONFERENCE']; else $ALLOW_CONFERENCE = "";
  if (isset($_POST['T_ALLOW_SMILEYS'])) $ALLOW_SMILEYS = $_POST['T_ALLOW_SMILEYS']; else $ALLOW_SMILEYS = "";
  if (isset($_POST['T_ALLOW_CHANGE_CONTACT_NICKNAME'])) $ALLOW_CHANGE_CONTACT_NICKNAME = $_POST['T_ALLOW_CHANGE_CONTACT_NICKNAME']; else $ALLOW_CHANGE_CONTACT_NICKNAME = "";
  if (isset($_POST['T_ALLOW_CHANGE_EMAIL_PHONE'])) $ALLOW_CHANGE_EMAIL_PHONE = $_POST['T_ALLOW_CHANGE_EMAIL_PHONE']; else $ALLOW_CHANGE_EMAIL_PHONE = "";
  if (isset($_POST['T_ALLOW_CHANGE_FUNCTION_NAME'])) $ALLOW_CHANGE_FUNCTION_NAME = $_POST['T_ALLOW_CHANGE_FUNCTION_NAME']; else $ALLOW_CHANGE_FUNCTION_NAME = "";
  if (isset($_POST['T_ALLOW_CHANGE_AVATAR'])) $ALLOW_CHANGE_AVATAR = $_POST['T_ALLOW_CHANGE_AVATAR']; else $ALLOW_CHANGE_AVATAR = "";
  if (isset($_POST['T_ALLOW_SEND_TO_OFFLINE_USER'])) $ALLOW_SEND_TO_OFFLINE_USER = $_POST['T_ALLOW_SEND_TO_OFFLINE_USER']; else $ALLOW_SEND_TO_OFFLINE_USER = "";
  if (isset($_POST['T_ALLOW_HISTORY_MESSAGES'])) $ALLOW_HISTORY_MESSAGES = $_POST['T_ALLOW_HISTORY_MESSAGES']; else $ALLOW_HISTORY_MESSAGES = "";
  if (isset($_POST['T_ALLOW_USE_PROXY'])) $ALLOW_USE_PROXY = $_POST['T_ALLOW_USE_PROXY']; else $ALLOW_USE_PROXY = "";
  if (isset($_POST['T_ALLOW_CONTACT_RATING'])) $ALLOW_CONTACT_RATING = $_POST['T_ALLOW_CONTACT_RATING']; else $ALLOW_CONTACT_RATING = "";
  if (isset($_POST['T_ALLOW_COL_FUNCTION_NAME'])) $ALLOW_COL_FUNCTION_NAME = $_POST['T_ALLOW_COL_FUNCTION_NAME']; else $ALLOW_COL_FUNCTION_NAME = "";
  if (isset($_POST['T_ALLOW_EMAIL_NOTIFIER'])) $ALLOW_EMAIL_NOTIFIER = $_POST['T_ALLOW_EMAIL_NOTIFIER']; else $ALLOW_EMAIL_NOTIFIER = "";
  if (isset($_POST['T_GROUP_FOR_SBX_AND_ADMIN_MSG'])) $GROUP_FOR_SBX_AND_ADMIN_MSG = $_POST['T_GROUP_FOR_SBX_AND_ADMIN_MSG']; else $GROUP_FOR_SBX_AND_ADMIN_MSG = "";
  if (isset($_POST['T_ENTERPRISE_SERVER'])) $ENTERPRISE_SERVER = $_POST['T_ENTERPRISE_SERVER']; else $ENTERPRISE_SERVER = "";
  if (isset($_POST['T_STATISTICS'])) $STATISTICS = $_POST['T_STATISTICS']; else $STATISTICS = "";
  if (isset($_POST['T_FORCE_AWAY_ON_SCREENSAVER'])) $FORCE_AWAY_ON_SCREENSAVER = $_POST['T_FORCE_AWAY_ON_SCREENSAVER']; else $FORCE_AWAY_ON_SCREENSAVER = "";
  if (isset($_POST['T_USER_HIEARCHIC_MANAGEMENT_BY_ADMIN'])) $USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = $_POST['T_USER_HIEARCHIC_MANAGEMENT_BY_ADMIN']; else $USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = "";
  if (isset($_POST['T_ALLOW_MANAGE_CONTACT_LIST'])) $ALLOW_MANAGE_CONTACT_LIST = $_POST['T_ALLOW_MANAGE_CONTACT_LIST']; else $ALLOW_MANAGE_CONTACT_LIST = "";
  if (isset($_POST['T_ALLOW_MANAGE_OPTIONS'])) $ALLOW_MANAGE_OPTIONS = $_POST['T_ALLOW_MANAGE_OPTIONS']; else $ALLOW_MANAGE_OPTIONS = "";
  if (isset($_POST['T_FORCE_STATUS_LIST_FROM_SERVER'])) $FORCE_STATUS_LIST_FROM_SERVER = $_POST['T_FORCE_STATUS_LIST_FROM_SERVER']; else $FORCE_STATUS_LIST_FROM_SERVER = "";
  if (isset($_POST['T_USER_NEED_PASSWORD'])) $USER_NEED_PASSWORD = $_POST['T_USER_NEED_PASSWORD']; else $USER_NEED_PASSWORD = "";
  if (isset($_POST['T_ALLOW_AUTO_ADD_NEW_USER_ON_SERVER'])) $ALLOW_AUTO_ADD_NEW_USER_ON_SERVER = $_POST['T_ALLOW_AUTO_ADD_NEW_USER_ON_SERVER']; else $ALLOW_AUTO_ADD_NEW_USER_ON_SERVER = "";
  if (isset($_POST['T_PENDING_NEW_AUTO_ADDED_USER'])) $PENDING_NEW_AUTO_ADDED_USER = $_POST['T_PENDING_NEW_AUTO_ADDED_USER']; else $PENDING_NEW_AUTO_ADDED_USER = "";
  if (isset($_POST['T_PENDING_USER_ON_COMPUTER_CHANGE'])) $PENDING_USER_ON_COMPUTER_CHANGE = $_POST['T_PENDING_USER_ON_COMPUTER_CHANGE']; else $PENDING_USER_ON_COMPUTER_CHANGE = "";
  if (isset($_POST['T_FORCE_UPDATE_BY_SERVER'])) $FORCE_UPDATE_BY_SERVER = $_POST['T_FORCE_UPDATE_BY_SERVER']; else $FORCE_UPDATE_BY_SERVER = "";
  if (isset($_POST['T_FORCE_UPDATE_BY_INTERNET'])) $FORCE_UPDATE_BY_INTERNET = $_POST['T_FORCE_UPDATE_BY_INTERNET']; else $FORCE_UPDATE_BY_INTERNET = "";
  if (isset($_POST['T_CRYPT_MESSAGES'])) $CRYPT_MESSAGES = $_POST['T_CRYPT_MESSAGES']; else $CRYPT_MESSAGES = "";
  if (isset($_POST['T_HISTORY_MESSAGES_ON_ACP'])) $HISTORY_MESSAGES_ON_ACP = $_POST['T_HISTORY_MESSAGES_ON_ACP']; else $HISTORY_MESSAGES_ON_ACP = "";
  if (isset($_POST['T_LOG_SESSION_OPEN'])) $LOG_SESSION_OPEN = $_POST['T_LOG_SESSION_OPEN']; else $LOG_SESSION_OPEN = "";
  if (isset($_POST['T_SEND_ADMIN_ALERT'])) $SEND_ADMIN_ALERT = $_POST['T_SEND_ADMIN_ALERT']; else $SEND_ADMIN_ALERT = "";
  if (isset($_POST['T_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL'])) $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL = $_POST['T_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL']; else $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL = "";
  if (isset($_POST['T_SLOW_NOTIFY'])) $SLOW_NOTIFY = $_POST['T_SLOW_NOTIFY']; else $SLOW_NOTIFY = "";
  if (isset($_POST['T_PUBLIC_OPTIONS_LIST'])) $PUBLIC_OPTIONS_LIST = $_POST['T_PUBLIC_OPTIONS_LIST']; else $PUBLIC_OPTIONS_LIST = "";
  if (isset($_POST['T_PUBLIC_USERS_LIST'])) $PUBLIC_USERS_LIST = $_POST['T_PUBLIC_USERS_LIST']; else $PUBLIC_USERS_LIST = "";
  if (isset($_POST['T_PUBLIC_POST_AVATAR'])) $PUBLIC_POST_AVATAR = $_POST['T_PUBLIC_POST_AVATAR']; else $PUBLIC_POST_AVATAR = "";
  if (isset($_POST['T_EXTERN_URL_TO_REGISTER'])) $EXTERN_URL_TO_REGISTER = $_POST['T_EXTERN_URL_TO_REGISTER']; else $EXTERN_URL_TO_REGISTER = "";
  if (isset($_POST['T_EXTERN_URL_FORGET_PASSWORD'])) $EXTERN_URL_FORGET_PASSWORD = $_POST['T_EXTERN_URL_FORGET_PASSWORD']; else $EXTERN_URL_FORGET_PASSWORD = "";
  if (isset($_POST['T_EXTERN_URL_CHANGE_PASSWORD'])) $EXTERN_URL_CHANGE_PASSWORD = $_POST['T_EXTERN_URL_CHANGE_PASSWORD']; else $EXTERN_URL_CHANGE_PASSWORD = "";
  if (isset($_POST['T_EXTERNAL_AUTHENTICATION'])) $EXTERNAL_AUTHENTICATION = $_POST['T_EXTERNAL_AUTHENTICATION']; else $EXTERNAL_AUTHENTICATION = "";
  if (isset($_POST['T_IM_ADDRESS_BOOK_PASSWORD'])) $IM_ADDRESS_BOOK_PASSWORD = $_POST['T_IM_ADDRESS_BOOK_PASSWORD']; else $IM_ADDRESS_BOOK_PASSWORD = "";
  if (isset($_POST['T_NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER'])) $NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER = $_POST['T_NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER']; else $NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER = "";
  if (isset($_POST['T_SITE_TITLE'])) $SITE_TITLE = trim($_POST['T_SITE_TITLE']); else $SITE_TITLE = "";
  if (isset($_POST['T_SITE_TITLE_TO_SHOW'])) $SITE_TITLE_TO_SHOW = $_POST['T_SITE_TITLE_TO_SHOW']; else $SITE_TITLE_TO_SHOW = "";
  if (isset($_POST['T_SITE_URL_TO_SHOW'])) $SITE_URL_TO_SHOW = $_POST['T_SITE_URL_TO_SHOW']; else $SITE_URL_TO_SHOW = "";
  if (isset($_POST['T_ADMIN_EMAIL'])) $ADMIN_EMAIL = $_POST['T_ADMIN_EMAIL']; else $ADMIN_EMAIL = "";
  if (isset($_POST['T_ADMIN_PHONE'])) $ADMIN_PHONE = $_POST['T_ADMIN_PHONE']; else $ADMIN_PHONE = "";
  if (isset($_POST['T_SCROLL_TEXT'])) $SCROLL_TEXT = $_POST['T_SCROLL_TEXT']; else $SCROLL_TEXT = "";
  if (isset($_POST['T_PROXY_ADDRESS'])) $PROXY_ADDRESS = $_POST['T_PROXY_ADDRESS']; else $PROXY_ADDRESS = "";
  if (isset($_POST['T_INCOMING_EMAIL_SERVER_ADDRESS'])) $INCOMING_EMAIL_SERVER_ADDRESS = $_POST['T_INCOMING_EMAIL_SERVER_ADDRESS']; else $INCOMING_EMAIL_SERVER_ADDRESS = "";
  if (isset($_POST['T_PASSWORD_FOR_PRIVATE_SERVER'])) $PASSWORD_FOR_PRIVATE_SERVER = $_POST['T_PASSWORD_FOR_PRIVATE_SERVER']; else $PASSWORD_FOR_PRIVATE_SERVER = "";
  if (isset($_POST['T_ALLOW_UPPERCASE_SPACE_USERNAME'])) $ALLOW_UPPERCASE_SPACE_USERNAME = $_POST['T_ALLOW_UPPERCASE_SPACE_USERNAME']; else $ALLOW_UPPERCASE_SPACE_USERNAME = "X";
  if (isset($_POST['T_CENSOR_MESSAGES'])) $CENSOR_MESSAGES = $_POST['T_CENSOR_MESSAGES']; else $CENSOR_MESSAGES = "";
  if (isset($_POST['T_PWD_NEED_DIGIT_LETTER'])) $PWD_NEED_DIGIT_LETTER = $_POST['T_PWD_NEED_DIGIT_LETTER']; else $PWD_NEED_DIGIT_LETTER = "";
  if (isset($_POST['T_PWD_NEED_UPPER_LOWER'])) $PWD_NEED_UPPER_LOWER = $_POST['T_PWD_NEED_UPPER_LOWER']; else $PWD_NEED_UPPER_LOWER = "";
  if (isset($_POST['T_PWD_NEED_SPECIAL_CHARACTER'])) $PWD_NEED_SPECIAL_CHARACTER = $_POST['T_PWD_NEED_SPECIAL_CHARACTER']; else $PWD_NEED_SPECIAL_CHARACTER = "";
  if (isset($_POST['T_SHOUTBOX'])) $SHOUTBOX = $_POST['T_SHOUTBOX']; else $SHOUTBOX = "";
  if (isset($_POST['T_SHOUTBOX_NEED_APPROVAL'])) $SHOUTBOX_NEED_APPROVAL = $_POST['T_SHOUTBOX_NEED_APPROVAL']; else $SHOUTBOX_NEED_APPROVAL = "";
  if (isset($_POST['T_SHOUTBOX_VOTE'])) $SHOUTBOX_VOTE = $_POST['T_SHOUTBOX_VOTE']; else $SHOUTBOX_VOTE = "";
  if (isset($_POST['T_GROUP_USER_CAN_JOIN'])) $GROUP_USER_CAN_JOIN = $_POST['T_GROUP_USER_CAN_JOIN']; else $GROUP_USER_CAN_JOIN = "";
  if (isset($_POST['T_SERVERS_STATUS'])) $SERVERS_STATUS = $_POST['T_SERVERS_STATUS']; else $SERVERS_STATUS = "";
  if (isset($_POST['T_CHECK_VERSION_INTERNET'])) $CHECK_VERSION_INTERNET = $_POST['T_CHECK_VERSION_INTERNET']; else $CHECK_VERSION_INTERNET = "";
  if (isset($_POST['T_TIME_ZONES'])) $TIME_ZONES = $_POST['T_TIME_ZONES']; else $TIME_ZONES = "";
  if (isset($_POST['T_SHOUTBOX_PUBLIC'])) $SHOUTBOX_PUBLIC = $_POST['T_SHOUTBOX_PUBLIC']; else $SHOUTBOX_PUBLIC = "";
  if (isset($_POST['T_BOOKMARKS'])) $BOOKMARKS = $_POST['T_BOOKMARKS']; else $BOOKMARKS = "";
  if (isset($_POST['T_BOOKMARKS_VOTE'])) $BOOKMARKS_VOTE = $_POST['T_BOOKMARKS_VOTE']; else $BOOKMARKS_VOTE = "";
  if (isset($_POST['T_BOOKMARKS_PUBLIC'])) $BOOKMARKS_PUBLIC = $_POST['T_BOOKMARKS_PUBLIC']; else $BOOKMARKS_PUBLIC = "";
  if (isset($_POST['T_BOOKMARKS_NEED_APPROVAL'])) $BOOKMARKS_NEED_APPROVAL = $_POST['T_BOOKMARKS_NEED_APPROVAL']; else $BOOKMARKS_NEED_APPROVAL = ""; 
  if (isset($_POST['T_ALLOW_MANAGE_PROFILE'])) $ALLOW_MANAGE_PROFILE = $_POST['T_ALLOW_MANAGE_PROFILE']; else $ALLOW_MANAGE_PROFILE = "";
  if (isset($_POST['T_INVITE_FILL_PROFILE_ON_FIRST_LOGIN'])) $INVITE_FILL_PROFILE_ON_FIRST_LOGIN = $_POST['T_INVITE_FILL_PROFILE_ON_FIRST_LOGIN']; else $INVITE_FILL_PROFILE_ON_FIRST_LOGIN = "";
  if (isset($_POST['T_ROLES_TO_OVERRIDE_PERMISSIONS'])) $ROLES_TO_OVERRIDE_PERMISSIONS = $_POST['T_ROLES_TO_OVERRIDE_PERMISSIONS']; else $ROLES_TO_OVERRIDE_PERMISSIONS = "";
  if (isset($_POST['T_WAIT_STARTUP_IF_SERVER_UNAVAILABLE'])) $WAIT_STARTUP_IF_SERVER_UNAVAILABLE = $_POST['T_WAIT_STARTUP_IF_SERVER_UNAVAILABLE']; else $WAIT_STARTUP_IF_SERVER_UNAVAILABLE = "";
  if (isset($_POST['T_FORCE_LAUNCH_ON_STARTUP'])) $FORCE_LAUNCH_ON_STARTUP = $_POST['T_FORCE_LAUNCH_ON_STARTUP']; else $FORCE_LAUNCH_ON_STARTUP = "";
  if (isset($_POST['T_ALLOW_SKIN'])) $ALLOW_SKIN = $_POST['T_ALLOW_SKIN']; else $ALLOW_SKIN = "";
  if (isset($_POST['T_ALLOW_CLOSE_IM'])) $ALLOW_CLOSE_IM = $_POST['T_ALLOW_CLOSE_IM']; else $ALLOW_CLOSE_IM = "";
  if (isset($_POST['T_ALLOW_SOUND_USAGE'])) $ALLOW_SOUND_USAGE = $_POST['T_ALLOW_SOUND_USAGE']; else $ALLOW_SOUND_USAGE = "";
  if (isset($_POST['T_ALLOW_REDUCE_MAIN_SCREEN'])) $ALLOW_REDUCE_MAIN_SCREEN = $_POST['T_ALLOW_REDUCE_MAIN_SCREEN']; else $ALLOW_REDUCE_MAIN_SCREEN = "";
  if (isset($_POST['T_ALLOW_REDUCE_MESSAGE_SCREEN'])) $ALLOW_REDUCE_MESSAGE_SCREEN = $_POST['T_ALLOW_REDUCE_MESSAGE_SCREEN']; else $ALLOW_REDUCE_MESSAGE_SCREEN = "";
  if (isset($_POST['T_SEND_ADMIN_ALERT_EMAIL'])) $SEND_ADMIN_ALERT_EMAIL = $_POST['T_SEND_ADMIN_ALERT_EMAIL']; else $SEND_ADMIN_ALERT_EMAIL = "";
  if (isset($_POST['T_ALLOW_POST_IT'])) $ALLOW_POST_IT = $_POST['T_ALLOW_POST_IT']; else $ALLOW_POST_IT = "";
  if (isset($_POST['T_SHARE_FILES'])) $SHARE_FILES = $_POST['T_SHARE_FILES']; else $SHARE_FILES = "";
  if (isset($_POST['T_SHARE_FILES_FTP_ADDRESS'])) $SHARE_FILES_FTP_ADDRESS = $_POST['T_SHARE_FILES_FTP_ADDRESS']; else $SHARE_FILES_FTP_ADDRESS = "";
  if (isset($_POST['T_SHARE_FILES_FTP_LOGIN'])) $SHARE_FILES_FTP_LOGIN = $_POST['T_SHARE_FILES_FTP_LOGIN']; else $SHARE_FILES_FTP_LOGIN = "";
  if (isset($_POST['T_SHARE_FILES_FTP_PASSWORD'])) $SHARE_FILES_FTP_PASSWORD = $_POST['T_SHARE_FILES_FTP_PASSWORD']; else $SHARE_FILES_FTP_PASSWORD = "";
  if (isset($_POST['T_SHARE_FILES_FTP_PASSWORD_CRYPT'])) $SHARE_FILES_FTP_PASSWORD_CRYPT = $_POST['T_SHARE_FILES_FTP_PASSWORD_CRYPT']; else $SHARE_FILES_FTP_PASSWORD_CRYPT = "";
  if (isset($_POST['T_SHARE_FILES_NEED_APPROVAL'])) $SHARE_FILES_NEED_APPROVAL = $_POST['T_SHARE_FILES_NEED_APPROVAL']; else $SHARE_FILES_NEED_APPROVAL = "";
  if (isset($_POST['T_SHARE_FILES_TRASH'])) $SHARE_FILES_TRASH = $_POST['T_SHARE_FILES_TRASH']; else $SHARE_FILES_TRASH = "";
  if (isset($_POST['T_SHARE_FILES_EXCHANGE'])) $SHARE_FILES_EXCHANGE = $_POST['T_SHARE_FILES_EXCHANGE']; else $SHARE_FILES_EXCHANGE = "";
  if (isset($_POST['T_SHARE_FILES_EXCHANGE_NEED_APPROVAL'])) $SHARE_FILES_EXCHANGE_NEED_APPROVAL = $_POST['T_SHARE_FILES_EXCHANGE_NEED_APPROVAL']; else $SHARE_FILES_EXCHANGE_NEED_APPROVAL = "";
  if (isset($_POST['T_SHARE_FILES_EXCHANGE_TRASH'])) $SHARE_FILES_EXCHANGE_TRASH = $_POST['T_SHARE_FILES_EXCHANGE_TRASH']; else $SHARE_FILES_EXCHANGE_TRASH = "";
  if (isset($_POST['T_SHARE_FILES_VOTE'])) $SHARE_FILES_VOTE = $_POST['T_SHARE_FILES_VOTE']; else $SHARE_FILES_VOTE = "";
  if (isset($_POST['T_SHARE_FILES_FOLDER'])) $SHARE_FILES_FOLDER = $_POST['T_SHARE_FILES_FOLDER']; else $SHARE_FILES_FOLDER = "";
  if (isset($_POST['T_SHARE_FILES_SCREENSHOT'])) $SHARE_FILES_SCREENSHOT = $_POST['T_SHARE_FILES_SCREENSHOT']; else $SHARE_FILES_SCREENSHOT = "";
  if (isset($_POST['T_SHARE_FILES_EXCHANGE_SCREENSHOT'])) $SHARE_FILES_EXCHANGE_SCREENSHOT = $_POST['T_SHARE_FILES_EXCHANGE_SCREENSHOT']; else $SHARE_FILES_EXCHANGE_SCREENSHOT = "";
  if (isset($_POST['T_SHARE_FILES_WEBCAM'])) $SHARE_FILES_WEBCAM = $_POST['T_SHARE_FILES_WEBCAM']; else $SHARE_FILES_WEBCAM = "";
  if (isset($_POST['T_SHARE_FILES_EXCHANGE_WEBCAM'])) $SHARE_FILES_EXCHANGE_WEBCAM = $_POST['T_SHARE_FILES_EXCHANGE_WEBCAM']; else $SHARE_FILES_EXCHANGE_WEBCAM = "";
  if (isset($_POST['T_SHARE_FILES_COMPRESS'])) $SHARE_FILES_COMPRESS = $_POST['T_SHARE_FILES_COMPRESS']; else $SHARE_FILES_COMPRESS = "";
  if (isset($_POST['T_SHARE_FILES_PROTECT'])) $SHARE_FILES_PROTECT = $_POST['T_SHARE_FILES_PROTECT']; else $SHARE_FILES_PROTECT = "";
  if (isset($_POST['T_SHARE_FILES_ALLOW_UPPERCASE'])) $SHARE_FILES_ALLOW_UPPERCASE = $_POST['T_SHARE_FILES_ALLOW_UPPERCASE']; else $SHARE_FILES_ALLOW_UPPERCASE = "";
  if (isset($_POST['T_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN'])) $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN = $_POST['T_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN']; else $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN = "";
  if (isset($_POST['T_ALLOW_HIDDEN_STATUS'])) $ALLOW_HIDDEN_STATUS = $_POST['T_ALLOW_HIDDEN_STATUS']; else $ALLOW_HIDDEN_STATUS = "";
  if (isset($_POST['T_ACP_PROTECT_BY_HTACCESS'])) $ACP_PROTECT_BY_HTACCESS = $_POST['T_ACP_PROTECT_BY_HTACCESS']; else $ACP_PROTECT_BY_HTACCESS = "";
  if (isset($_POST['T_ACP_ALLOW_MEMORY_AUTH'])) $ACP_ALLOW_MEMORY_AUTH = $_POST['T_ACP_ALLOW_MEMORY_AUTH']; else $ACP_ALLOW_MEMORY_AUTH = "";
  if (isset($_POST['T_ALLOW_HISTORY_MESSAGES_EXPORT'])) $ALLOW_HISTORY_MESSAGES_EXPORT = $_POST['T_ALLOW_HISTORY_MESSAGES_EXPORT']; else $ALLOW_HISTORY_MESSAGES_EXPORT = "";
  if (isset($_POST['T_BACKUP_FILES'])) $BACKUP_FILES = $_POST['T_BACKUP_FILES']; else $BACKUP_FILES = "";
  if (isset($_POST['T_BACKUP_FILES_ALLOW_MULTI_FOLDERS'])) $BACKUP_FILES_ALLOW_MULTI_FOLDERS = $_POST['T_BACKUP_FILES_ALLOW_MULTI_FOLDERS']; else $BACKUP_FILES_ALLOW_MULTI_FOLDERS = "";
  if (isset($_POST['T_BACKUP_FILES_ALLOW_SUB_FOLDERS'])) $BACKUP_FILES_ALLOW_SUB_FOLDERS = $_POST['T_BACKUP_FILES_ALLOW_SUB_FOLDERS']; else $BACKUP_FILES_ALLOW_SUB_FOLDERS = "";
  if (isset($_POST['T_BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY'])) $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY = $_POST['T_BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY']; else $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY = "";
  if (isset($_POST['T_BACKUP_FILES_FTP_ADDRESS'])) $BACKUP_FILES_FTP_ADDRESS = $_POST['T_BACKUP_FILES_FTP_ADDRESS']; else $BACKUP_FILES_FTP_ADDRESS = "";
  if (isset($_POST['T_BACKUP_FILES_FTP_LOGIN'])) $BACKUP_FILES_FTP_LOGIN = $_POST['T_BACKUP_FILES_FTP_LOGIN']; else $BACKUP_FILES_FTP_LOGIN = "";
  if (isset($_POST['T_BACKUP_FILES_FTP_PASSWORD'])) $BACKUP_FILES_FTP_PASSWORD = $_POST['T_BACKUP_FILES_FTP_PASSWORD']; else $BACKUP_FILES_FTP_PASSWORD = "";
  if (isset($_POST['T_BACKUP_FILES_FTP_PASSWORD_CRYPT'])) $BACKUP_FILES_FTP_PASSWORD_CRYPT = $_POST['T_BACKUP_FILES_FTP_PASSWORD_CRYPT']; else $BACKUP_FILES_FTP_PASSWORD_CRYPT = "";
  if (isset($_POST['T_BACKUP_FILES_FOLDER'])) $BACKUP_FILES_FOLDER = $_POST['T_BACKUP_FILES_FOLDER']; else $BACKUP_FILES_FOLDER = "BACKUP_FILES_FOLDER";
  if (isset($_POST['T_BACKUP_FILES_FORCE_EVERY_DAY_AT'])) $BACKUP_FILES_FORCE_EVERY_DAY_AT = $_POST['T_BACKUP_FILES_FORCE_EVERY_DAY_AT']; else $BACKUP_FILES_FORCE_EVERY_DAY_AT = "";
  if (isset($_POST['T_SHARE_FILES_ALLOW_ACCENT'])) $SHARE_FILES_ALLOW_ACCENT = $_POST['T_SHARE_FILES_ALLOW_ACCENT']; else $SHARE_FILES_ALLOW_ACCENT = "";
  if (isset($_POST['T_FORCE_OPTION_FILE_FROM_SERVER'])) $FORCE_OPTION_FILE_FROM_SERVER = $_POST['T_FORCE_OPTION_FILE_FROM_SERVER']; else $FORCE_OPTION_FILE_FROM_SERVER = "";
  if (isset($_POST['T_SHOUTBOX_ALLOW_SCROLLING'])) $SHOUTBOX_ALLOW_SCROLLING = $_POST['T_SHOUTBOX_ALLOW_SCROLLING']; else $SHOUTBOX_ALLOW_SCROLLING = "";
  //if (isset($_POST['T_'])) $XXXXXX = $_POST['T_']; else $XXXXXX = "";
  //if (isset($_POST['T_'])) $XXXXXX = $_POST['T_']; else $XXXXXX = "";
  //if (isset($_POST['T_'])) $XXXXXX = $_POST['T_']; else $XXXXXX = "";
  //
  // -------------------------------------- Numeric options --------------------------------------
  $MAX_NB_USER = intval($_POST['T_MAX_NB_USER']);
  $MAX_NB_SESSION = intval($_POST['T_MAX_NB_SESSION']);
  $MAX_NB_CONTACT_BY_USER = intval($_POST['T_MAX_NB_CONTACT_BY_USER']);
  $MAX_NB_IP = intval($_POST['T_MAX_NB_IP']);
  $CHECK_NEW_MSG_EVERY = intval($_POST['T_CHECK_NEW_MSG_EVERY']);
  $OUTOFDATE_AFTER_NOT_USE_DURATION = intval($_POST['T_OUTOFDATE_AFTER_NOT_USE_DURATION']);
  $MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER = intval($_POST['T_MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER']);
  $PROXY_PORT_NUMBER = intval($_POST['T_PROXY_PORT_NUMBER']);
  $MINIMUM_USERNAME_LENGTH = intval($_POST['T_MINIMUM_USERNAME_LENGTH']);
  $MINIMUM_PASSWORD_LENGTH = intval($_POST['T_MINIMUM_PASSWORD_LENGTH']);
  $SHOUTBOX_REFRESH_DELAY = intval($_POST['T_SHOUTBOX_REFRESH_DELAY']);
  $SHOUTBOX_STORE_DAYS = intval($_POST['T_SHOUTBOX_STORE_DAYS']);
  $SHOUTBOX_STORE_MAX = intval($_POST['T_SHOUTBOX_STORE_MAX']);
  $SHOUTBOX_QUOTA_USER_DAY = intval($_POST['T_SHOUTBOX_QUOTA_USER_DAY']);
  $SHOUTBOX_QUOTA_USER_WEEK = intval($_POST['T_SHOUTBOX_QUOTA_USER_WEEK']);
  $SHOUTBOX_APPROVAL_QUEUE_USER = intval($_POST['T_SHOUTBOX_APPROVAL_QUEUE_USER']);
  $SHOUTBOX_APPROVAL_QUEUE = intval($_POST['T_SHOUTBOX_APPROVAL_QUEUE']);
  $SHOUTBOX_LOCK_USER_APPROVAL = intval($_POST['T_SHOUTBOX_LOCK_USER_APPROVAL']);
  $SHOUTBOX_MAX_NOTES_USER_DAY = intval($_POST['T_SHOUTBOX_MAX_NOTES_USER_DAY']);
  $SHOUTBOX_MAX_NOTES_USER_WEEK = intval($_POST['T_SHOUTBOX_MAX_NOTES_USER_WEEK']);
  $SHOUTBOX_REMOVE_MESSAGE_VOTES = intval($_POST['T_SHOUTBOX_REMOVE_MESSAGE_VOTES']);
  $SHOUTBOX_LOCK_USER_VOTES = intval($_POST['T_SHOUTBOX_LOCK_USER_VOTES']);
  $LOCK_DURATION = intval($_POST['T_LOCK_DURATION']);
  $UNREAD_MESSAGE_VALIDITY = intval($_POST['T_UNREAD_MESSAGE_VALIDITY']);
  $LOCK_AFTER_NO_CONTACT_DURATION = intval($_POST['T_LOCK_AFTER_NO_CONTACT_DURATION']);
  $LOCK_AFTER_NO_ACTIVITY_DURATION = intval($_POST['T_LOCK_AFTER_NO_ACTIVITY_DURATION']);
  $PASSWORD_VALIDITY = intval($_POST['T_PASSWORD_VALIDITY']);
  $SHARE_FILES_FTP_PORT_NUMBER = intval($_POST['T_SHARE_FILES_FTP_PORT_NUMBER']);
  $SHARE_FILES_MAX_FILE_SIZE = intval($_POST['T_SHARE_FILES_MAX_FILE_SIZE']);
  $SHARE_FILES_MAX_NB_FILES_TOTAL = intval($_POST['T_SHARE_FILES_MAX_NB_FILES_TOTAL']);
  $SHARE_FILES_MAX_NB_FILES_USER = intval($_POST['T_SHARE_FILES_MAX_NB_FILES_USER']);
  $SHARE_FILES_MAX_SPACE_SIZE_TOTAL = intval($_POST['T_SHARE_FILES_MAX_SPACE_SIZE_TOTAL']);
  $SHARE_FILES_MAX_SPACE_SIZE_USER = intval($_POST['T_SHARE_FILES_MAX_SPACE_SIZE_USER']);
  $SHARE_FILES_APPROVAL_QUEUE = intval($_POST['T_SHARE_FILES_APPROVAL_QUEUE']);
  $SHARE_FILES_QUOTA_FILES_USER_WEEK = intval($_POST['T_SHARE_FILES_QUOTA_FILES_USER_WEEK']);
  $SHARE_FILES_EXCHANGE_UNREAD_VALIDITY = intval($_POST['T_SHARE_FILES_EXCHANGE_UNREAD_VALIDITY']);
  $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_DAY = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_DAY']);
  $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_WEEK = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_WEEK']);
  $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_MONTH = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_MONTH']);
  $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_DAY = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_DAY']);
  $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_WEEK = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_WEEK']);
  $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_MONTH = intval($_POST['T_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_MONTH']);
  $ROLE_ID_DEFAULT_FOR_NEW_USER = intval($_POST['T_ROLE_ID_DEFAULT_FOR_NEW_USER']);
  $BACKUP_FILES_MAX_NB_ARCHIVES_USER = intval($_POST['T_BACKUP_FILES_MAX_NB_ARCHIVES_USER']);
  $BACKUP_FILES_MAX_ARCHIVE_SIZE = intval($_POST['T_BACKUP_FILES_MAX_ARCHIVE_SIZE']);
  $BACKUP_FILES_MAX_SPACE_SIZE_USER = intval($_POST['T_BACKUP_FILES_MAX_SPACE_SIZE_USER']);
  $BACKUP_FILES_MAX_SPACE_SIZE_TOTAL = intval($_POST['T_BACKUP_FILES_MAX_SPACE_SIZE_TOTAL']);
  $BACKUP_FILES_FTP_PORT_NUMBER = intval($_POST['T_BACKUP_FILES_FTP_PORT_NUMBER']);
  $GROUP_ID_DEFAULT_FOR_NEW_USER = intval($_POST['T_GROUP_ID_DEFAULT_FOR_NEW_USER']);
  //
  // -------------------------------------- Hidden options --------------------------------------
  $LANG = $_POST['T_LANG'];
  $AWAY_REASONS_LIST = trim($_POST['T_AWAY_REASONS_LIST']);
  $ONLINE_REASONS_LIST = trim($_POST['T_ONLINE_REASONS_LIST']);
  $BUSY_REASONS_LIST = trim($_POST['T_BUSY_REASONS_LIST']);
  $DONOTDISTURB_REASONS_LIST = trim($_POST['T_DONOTDISTURB_REASONS_LIST']);
  $PUBLIC_FOLDER = trim($_POST['T_PUBLIC_FOLDER']);
  $SKIN_FORCED_COLOR_CUSTOM_VERSION = trim($_POST['T_SKIN_FORCED_COLOR_CUSTOM_VERSION']);
  $AUTO_ADD_CONTACT_USER_ID = trim($_POST['T_AUTO_ADD_CONTACT_USER_ID']);
  $special_mode = $_POST['special_mode'];
  //$SPECIAL_MODE_OPEN_COMMUNITY = $_POST['T_SPECIAL_MODE_OPEN_COMMUNITY'];
  //$SPECIAL_MODE_GROUP_COMMUNITY = $_POST['T_SPECIAL_MODE_GROUP_COMMUNITY'];
  //$SPECIAL_MODE_OPEN_GROUP_COMMUNITY = $_POST['T_SPECIAL_MODE_OPEN_GROUP_COMMUNITY'];
  //
  // -------------------------------------- Boolean options --------------------------------------
  if ($MAINTENANCE_MODE != "") $MAINTENANCE_MODE = "X";
  if ($FLAG_COUNTRY_FROM_IP != "") $FLAG_COUNTRY_FROM_IP = "X";
  if ($FORCE_USERNAME_TO_PC_SESSION_NAME != "") $FORCE_USERNAME_TO_PC_SESSION_NAME = "X";
  if ($ALLOW_HIDDEN_TO_CONTACTS != "") $ALLOW_HIDDEN_TO_CONTACTS = "X";
  if ($ALLOW_CONFERENCE != "") $ALLOW_CONFERENCE = "X";
  if ($ALLOW_SMILEYS != "") $ALLOW_SMILEYS = "X";
  if ($ALLOW_CHANGE_CONTACT_NICKNAME != "") $ALLOW_CHANGE_CONTACT_NICKNAME = "X";
  if ($ALLOW_CHANGE_EMAIL_PHONE != "") $ALLOW_CHANGE_EMAIL_PHONE = "X";
  if ($ALLOW_CHANGE_FUNCTION_NAME != "") $ALLOW_CHANGE_FUNCTION_NAME = "X";
  if ($ALLOW_CHANGE_AVATAR != "") $ALLOW_CHANGE_AVATAR = "X";
  if ($ALLOW_SEND_TO_OFFLINE_USER != "") $ALLOW_SEND_TO_OFFLINE_USER = "X";
  if ($ALLOW_HISTORY_MESSAGES != "") $ALLOW_HISTORY_MESSAGES = "X";
  if ($ALLOW_USE_PROXY != "") $ALLOW_USE_PROXY = "X";
  //if ($ALLOW_CONTACT_RATING != "") $ALLOW_CONTACT_RATING = "X"; NON ! 
  if ($ALLOW_EMAIL_NOTIFIER != "") $ALLOW_EMAIL_NOTIFIER = "X";
  if ($GROUP_FOR_SBX_AND_ADMIN_MSG != "") $GROUP_FOR_SBX_AND_ADMIN_MSG = "X";
  if ($ENTERPRISE_SERVER != "") $ENTERPRISE_SERVER = "X";
  if ($STATISTICS != "") $STATISTICS = "X";
  if ($FORCE_AWAY_ON_SCREENSAVER != "") $FORCE_AWAY_ON_SCREENSAVER = "X";
  if ($USER_HIEARCHIC_MANAGEMENT_BY_ADMIN != "") $USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = "X";
  if ($ALLOW_MANAGE_CONTACT_LIST != "") $ALLOW_MANAGE_CONTACT_LIST = "X";
  if ($ALLOW_MANAGE_OPTIONS != "") $ALLOW_MANAGE_OPTIONS = "X";
  if ($FORCE_STATUS_LIST_FROM_SERVER != "") $FORCE_STATUS_LIST_FROM_SERVER = "X";
  if ($USER_NEED_PASSWORD != "") $USER_NEED_PASSWORD = "X";
  if ($ALLOW_AUTO_ADD_NEW_USER_ON_SERVER != "") $ALLOW_AUTO_ADD_NEW_USER_ON_SERVER = "X";
  if ($PENDING_NEW_AUTO_ADDED_USER != "") $PENDING_NEW_AUTO_ADDED_USER = "X";
  if ($PENDING_USER_ON_COMPUTER_CHANGE != "") $PENDING_USER_ON_COMPUTER_CHANGE = "X";
  if ($FORCE_UPDATE_BY_SERVER != "") $FORCE_UPDATE_BY_SERVER = "X";
  if ($FORCE_UPDATE_BY_INTERNET != "") $FORCE_UPDATE_BY_INTERNET = "X";
  if ($CRYPT_MESSAGES != "") $CRYPT_MESSAGES = "X";
  if ($HISTORY_MESSAGES_ON_ACP != "") $HISTORY_MESSAGES_ON_ACP = "X";
  if ($LOG_SESSION_OPEN != "") $LOG_SESSION_OPEN = "X";
  if ($SEND_ADMIN_ALERT != "") $SEND_ADMIN_ALERT = "X";
  if ($SLOW_NOTIFY != "") $SLOW_NOTIFY = "X";
  if ($PUBLIC_OPTIONS_LIST != "") $PUBLIC_OPTIONS_LIST = "X";
  if ($PUBLIC_USERS_LIST != "") $PUBLIC_USERS_LIST = "X";
  if ($PUBLIC_POST_AVATAR != "") $PUBLIC_POST_AVATAR = "X";
  if ($NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER != "") $NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER = "X";
  if ($CENSOR_MESSAGES != "") $CENSOR_MESSAGES = "X";
  if ($PWD_NEED_DIGIT_LETTER != "") $PWD_NEED_DIGIT_LETTER = "X";
  if ($PWD_NEED_UPPER_LOWER != "") $PWD_NEED_UPPER_LOWER = "X";
  if ($PWD_NEED_SPECIAL_CHARACTER != "") $PWD_NEED_SPECIAL_CHARACTER = "X";
  if ($SHOUTBOX != "") $SHOUTBOX = "X";
  if ($SHOUTBOX_NEED_APPROVAL != "") $SHOUTBOX_NEED_APPROVAL = "X";
  if ($SHOUTBOX_VOTE != "") $SHOUTBOX_VOTE = "X";
  if ($GROUP_USER_CAN_JOIN != "") $GROUP_USER_CAN_JOIN = "X";
  if ($SERVERS_STATUS != "") $SERVERS_STATUS = "X";
  if ($CHECK_VERSION_INTERNET != "") $CHECK_VERSION_INTERNET = "X";
  if ($TIME_ZONES != "") $TIME_ZONES = "X";
  if ($SHOUTBOX_PUBLIC != "") $SHOUTBOX_PUBLIC = "X";
  if ($BOOKMARKS != "") $BOOKMARKS = "X";
  if ($BOOKMARKS_VOTE != "") $BOOKMARKS_VOTE = "X";
  if ($BOOKMARKS_PUBLIC != "") $BOOKMARKS_PUBLIC = "X";
  if ($BOOKMARKS_NEED_APPROVAL != "") $BOOKMARKS_NEED_APPROVAL = "X";
  if ($ALLOW_MANAGE_PROFILE != "") $ALLOW_MANAGE_PROFILE = "X";
  if ($INVITE_FILL_PROFILE_ON_FIRST_LOGIN != "") $INVITE_FILL_PROFILE_ON_FIRST_LOGIN = "X";
  if ($ROLES_TO_OVERRIDE_PERMISSIONS != "") $ROLES_TO_OVERRIDE_PERMISSIONS = "X";
  if ($WAIT_STARTUP_IF_SERVER_UNAVAILABLE != "") $WAIT_STARTUP_IF_SERVER_UNAVAILABLE = "X";
  if ($ALLOW_UPPERCASE_SPACE_USERNAME != "") $ALLOW_UPPERCASE_SPACE_USERNAME = "X";
  if ($FORCE_LAUNCH_ON_STARTUP != "") $FORCE_LAUNCH_ON_STARTUP = "X";
  if ($ALLOW_SKIN != "") $ALLOW_SKIN = "X";
  if ($ALLOW_CLOSE_IM != "") $ALLOW_CLOSE_IM = "X";
  if ($ALLOW_SOUND_USAGE != "") $ALLOW_SOUND_USAGE = "X";
  if ($ALLOW_REDUCE_MAIN_SCREEN != "") $ALLOW_REDUCE_MAIN_SCREEN = "X";
  if ($ALLOW_REDUCE_MESSAGE_SCREEN != "") $ALLOW_REDUCE_MESSAGE_SCREEN = "X";
  if ($SEND_ADMIN_ALERT_EMAIL != "") $SEND_ADMIN_ALERT_EMAIL = "X";
  if ($ALLOW_POST_IT != "") $ALLOW_POST_IT = "X";
  if ($SHARE_FILES != "") $SHARE_FILES = "X";
  if ($SHARE_FILES_NEED_APPROVAL != "") $SHARE_FILES_NEED_APPROVAL = "X";
  if ($SHARE_FILES_TRASH != "") $SHARE_FILES_TRASH = "X";
  if ($SHARE_FILES_EXCHANGE != "") $SHARE_FILES_EXCHANGE = "X";
  if ($SHARE_FILES_EXCHANGE_NEED_APPROVAL != "") $SHARE_FILES_EXCHANGE_NEED_APPROVAL = "X";
  if ($SHARE_FILES_EXCHANGE_TRASH != "") $SHARE_FILES_EXCHANGE_TRASH = "X";
  if ($SHARE_FILES_VOTE != "") $SHARE_FILES_VOTE = "X";
  if ($SHARE_FILES_COMPRESS != "") $SHARE_FILES_COMPRESS = "X";
  if ($SHARE_FILES_PROTECT != "") $SHARE_FILES_PROTECT = "X";
  if ($SHARE_FILES_ALLOW_UPPERCASE != "") $SHARE_FILES_ALLOW_UPPERCASE = "X";
  if ($SHARE_FILES_SCREENSHOT != "") $SHARE_FILES_SCREENSHOT = "X";
  if ($SHARE_FILES_EXCHANGE_SCREENSHOT != "") $SHARE_FILES_EXCHANGE_SCREENSHOT = "X";
  if ($SHARE_FILES_ALLOW_ACCENT != "") $SHARE_FILES_ALLOW_ACCENT = "X";
  if ($ALLOW_HIDDEN_STATUS != "") $ALLOW_HIDDEN_STATUS = "X";
  if ($ACP_PROTECT_BY_HTACCESS != "") $ACP_PROTECT_BY_HTACCESS = "X";
  if ($ACP_ALLOW_MEMORY_AUTH != "") $ACP_ALLOW_MEMORY_AUTH = "X";
  if ($ALLOW_HISTORY_MESSAGES_EXPORT != "") $ALLOW_HISTORY_MESSAGES_EXPORT = "X";
  if ($BACKUP_FILES != "") $BACKUP_FILES = "X";
  if ($BACKUP_FILES_ALLOW_MULTI_FOLDERS != "") $BACKUP_FILES_ALLOW_MULTI_FOLDERS = "X";
  if ($BACKUP_FILES_ALLOW_SUB_FOLDERS != "") $BACKUP_FILES_ALLOW_SUB_FOLDERS = "X";
  if ($FORCE_OPTION_FILE_FROM_SERVER != "") $FORCE_OPTION_FILE_FROM_SERVER = "X";
  if ($SHOUTBOX_ALLOW_SCROLLING != "") $SHOUTBOX_ALLOW_SCROLLING = "X";
  //
  $SPECIAL_MODE_OPEN_COMMUNITY = "";
  $SPECIAL_MODE_GROUP_COMMUNITY = "";
  $SPECIAL_MODE_OPEN_GROUP_COMMUNITY = "";
  if ($special_mode == "2") $SPECIAL_MODE_GROUP_COMMUNITY = "X";
  if ($special_mode == "3") $SPECIAL_MODE_OPEN_COMMUNITY = "X";
  if ($special_mode == "4") $SPECIAL_MODE_OPEN_GROUP_COMMUNITY = "X";
  //
  // -------------------------------------- Controles --------------------------------------
  $PUBLIC_FOLDER =      trim($PUBLIC_FOLDER);
  $SCROLL_TEXT =        trim($SCROLL_TEXT);
  $SITE_TITLE =         trim($SITE_TITLE);
  $SITE_TITLE_TO_SHOW = trim($SITE_TITLE_TO_SHOW);
  $SITE_URL_TO_SHOW =   trim($SITE_URL_TO_SHOW);
  $SHARE_FILES_FOLDER =       trim($SHARE_FILES_FOLDER);
  $SHARE_FILES_FTP_ADDRESS =  trim($SHARE_FILES_FTP_ADDRESS);
  $SHARE_FILES_FTP_LOGIN =    trim($SHARE_FILES_FTP_LOGIN);
  $SHARE_FILES_FTP_PASSWORD = trim($SHARE_FILES_FTP_PASSWORD);
  $SHARE_FILES_FTP_PASSWORD_CRYPT = trim($SHARE_FILES_FTP_PASSWORD_CRYPT);
  $INCOMING_EMAIL_SERVER_ADDRESS =  trim($INCOMING_EMAIL_SERVER_ADDRESS);
  $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY =  trim($BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY);
  $BACKUP_FILES_FTP_ADDRESS =  trim($BACKUP_FILES_FTP_ADDRESS);
  $BACKUP_FILES_FTP_LOGIN =  trim($BACKUP_FILES_FTP_LOGIN);
  $BACKUP_FILES_FTP_PASSWORD =  trim($BACKUP_FILES_FTP_PASSWORD);
  $BACKUP_FILES_FTP_PASSWORD_CRYPT =  trim($BACKUP_FILES_FTP_PASSWORD_CRYPT);
  $BACKUP_FILES_FOLDER =  trim($BACKUP_FILES_FOLDER);
  $BACKUP_FILES_FORCE_EVERY_DAY_AT =  trim($BACKUP_FILES_FORCE_EVERY_DAY_AT);
  //
  $PUBLIC_FOLDER =      str_replace("'", "`", $PUBLIC_FOLDER);
  //$SCROLL_TEXT =        str_replace("'", "`", $SCROLL_TEXT);
  //$SITE_TITLE =         str_replace("'", "`", $SITE_TITLE);
  //$SITE_TITLE_TO_SHOW = str_replace("'", "`", $SITE_TITLE_TO_SHOW);
  //$SITE_URL_TO_SHOW =   str_replace("'", "", $SITE_URL_TO_SHOW);
  //$ADMIN_EMAIL =        str_replace("'", "", $ADMIN_EMAIL);
  //$ADMIN_PHONE =        str_replace("'", "", $ADMIN_PHONE);
  $PROXY_ADDRESS =      str_replace("'", "", $PROXY_ADDRESS);
  //$AWAY_REASONS_LIST =  str_replace("'", "", $AWAY_REASONS_LIST);
  $AWAY_REASONS_LIST =  str_replace("#", "", $AWAY_REASONS_LIST);
  //$ONLINE_REASONS_LIST =  str_replace("'", "", $ONLINE_REASONS_LIST);
  $ONLINE_REASONS_LIST =  str_replace("#", "", $ONLINE_REASONS_LIST);
  //$BUSY_REASONS_LIST =    str_replace("'", "", $BUSY_REASONS_LIST);
  $BUSY_REASONS_LIST =    str_replace("#", "", $BUSY_REASONS_LIST);
  //$DONOTDISTURB_REASONS_LIST =  str_replace("'", "", $DONOTDISTURB_REASONS_LIST);
  $DONOTDISTURB_REASONS_LIST =  str_replace("#", "", $DONOTDISTURB_REASONS_LIST);
  $INCOMING_EMAIL_SERVER_ADDRESS =  str_replace("'", "", $INCOMING_EMAIL_SERVER_ADDRESS);
  $SHARE_FILES_FOLDER =             str_replace("'", "", $SHARE_FILES_FOLDER);
  $SHARE_FILES_FTP_ADDRESS =        str_replace("'", "", $SHARE_FILES_FTP_ADDRESS);
  $SHARE_FILES_FTP_LOGIN =          str_replace("'", "", $SHARE_FILES_FTP_LOGIN);
  $SHARE_FILES_FTP_PASSWORD =       str_replace("'", "", $SHARE_FILES_FTP_PASSWORD);
  $SHARE_FILES_FTP_PASSWORD_CRYPT = str_replace("'", "", $SHARE_FILES_FTP_PASSWORD_CRYPT);
  $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY =   str_replace("'", "", $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY);
  $BACKUP_FILES_FOLDER =                   str_replace("'", "", $BACKUP_FILES_FOLDER);
  $BACKUP_FILES_FTP_ADDRESS =              str_replace("'", "", $BACKUP_FILES_FTP_ADDRESS);
  $BACKUP_FILES_FTP_LOGIN =                str_replace("'", "", $BACKUP_FILES_FTP_LOGIN);
  $BACKUP_FILES_FTP_PASSWORD =             str_replace("'", "", $BACKUP_FILES_FTP_PASSWORD);
  $BACKUP_FILES_FTP_PASSWORD_CRYPT =       str_replace("'", "", $BACKUP_FILES_FTP_PASSWORD_CRYPT);
  //
  //
  // Corriger les options
  //
  if ($MAX_NB_USER <= 0) $MAX_NB_USER = "0";  // 0 : unlimited
  if ($MAX_NB_SESSION <= 0) $MAX_NB_SESSION = "0";  // 0 : unlimited
  if ($MAX_NB_CONTACT_BY_USER <= 0) $MAX_NB_CONTACT_BY_USER = "0";  // 0 : unlimited
  if ($MAX_NB_IP <= 0) $MAX_NB_IP = "0";
  if ($CHECK_NEW_MSG_EVERY < 10) {$CHECK_NEW_MSG_EVERY = "20"; $nb_corrections++; $options_fixed .= "CHECK_NEW_MSG_EVERY#"; }
  //if ($MINIMUM_USERNAME_LENGTH < 2) {$MINIMUM_USERNAME_LENGTH = "2"; $nb_corrections++; $options_fixed .= "MINIMUM_USERNAME_LENGTH#"; }
  if ($MINIMUM_USERNAME_LENGTH < 2) $MINIMUM_USERNAME_LENGTH = "2";
  if ($MINIMUM_USERNAME_LENGTH > 10) {$MINIMUM_USERNAME_LENGTH = "10"; $nb_corrections++; $options_fixed .= "MINIMUM_USERNAME_LENGTH#"; }
  //if ($MINIMUM_PASSWORD_LENGTH < 4) {$MINIMUM_PASSWORD_LENGTH = "4"; $nb_corrections++; $options_fixed .= "MINIMUM_PASSWORD_LENGTH#"; }
  if ($MINIMUM_PASSWORD_LENGTH < 4) $MINIMUM_PASSWORD_LENGTH = "4";
  if ($MINIMUM_PASSWORD_LENGTH > 20) { $MINIMUM_PASSWORD_LENGTH = "20"; $nb_corrections++; $options_fixed .= "MINIMUM_PASSWORD_LENGTH#"; }
  if ($OUTOFDATE_AFTER_NOT_USE_DURATION <= 9) $OUTOFDATE_AFTER_NOT_USE_DURATION = "90";
  if ($OUTOFDATE_AFTER_NOT_USE_DURATION > 999) $OUTOFDATE_AFTER_NOT_USE_DURATION = "999";
  if ($MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER <= 0) $MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER = "10";
  if ($MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER > 99) $MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER = "10";
  if ($SHOUTBOX_REFRESH_DELAY <= 10) $SHOUTBOX_REFRESH_DELAY = "30";
  if ($SHOUTBOX_REFRESH_DELAY > 120) $SHOUTBOX_REFRESH_DELAY = "90";
  if ($SHOUTBOX_STORE_DAYS <= 0) $SHOUTBOX_STORE_DAYS = "30";
  if ($SHOUTBOX_STORE_DAYS > 99) $SHOUTBOX_STORE_DAYS = "90";
  if ($SHOUTBOX_STORE_MAX <= 5) $SHOUTBOX_STORE_MAX = "50";
  if ($SHOUTBOX_STORE_MAX > 999) $SHOUTBOX_STORE_MAX = "900";
  if ($SHOUTBOX_APPROVAL_QUEUE_USER <= 0) $SHOUTBOX_APPROVAL_QUEUE_USER = "3";
  if ($SHOUTBOX_APPROVAL_QUEUE_USER > 9) $SHOUTBOX_APPROVAL_QUEUE_USER = "9";
  if ($SHOUTBOX_APPROVAL_QUEUE <= 1) $SHOUTBOX_APPROVAL_QUEUE = "10";
  if ($SHOUTBOX_APPROVAL_QUEUE > 99) $SHOUTBOX_APPROVAL_QUEUE = "90";
  if ($LOCK_DURATION < 5) $LOCK_DURATION = "0";  // 0 : unlimited
  if ($LOCK_DURATION > 9999) $LOCK_DURATION = "9000";
  if ($UNREAD_MESSAGE_VALIDITY <= 1) $UNREAD_MESSAGE_VALIDITY = "0"; // 0 : unlimited
  if ($UNREAD_MESSAGE_VALIDITY > 99) $UNREAD_MESSAGE_VALIDITY = "90";
  if ($LOCK_AFTER_NO_CONTACT_DURATION < 10) $LOCK_AFTER_NO_CONTACT_DURATION = "0"; // 0 : disable
  if ($LOCK_AFTER_NO_CONTACT_DURATION > 99) $LOCK_AFTER_NO_CONTACT_DURATION = "90";
  if ($LOCK_AFTER_NO_ACTIVITY_DURATION < 10) $LOCK_AFTER_NO_ACTIVITY_DURATION = "0"; // 0 : disable
  if ($LOCK_AFTER_NO_ACTIVITY_DURATION > 99) $LOCK_AFTER_NO_ACTIVITY_DURATION = "90";
  if ($PASSWORD_VALIDITY < 10) $PASSWORD_VALIDITY = "0"; // 0 : disable
  if ($PASSWORD_VALIDITY > 365) $PASSWORD_VALIDITY = "365";
  if ($SHARE_FILES_APPROVAL_QUEUE < 10) $SHARE_FILES_APPROVAL_QUEUE = "20";
  if ($SHARE_FILES_APPROVAL_QUEUE > 99) $SHARE_FILES_APPROVAL_QUEUE = "99";
  if ($SHARE_FILES_EXCHANGE_UNREAD_VALIDITY < 10) $SHARE_FILES_EXCHANGE_UNREAD_VALIDITY = "30";
  if ($SHARE_FILES_EXCHANGE_UNREAD_VALIDITY > 99) $SHARE_FILES_EXCHANGE_UNREAD_VALIDITY = "99";
  if ($BACKUP_FILES_MAX_NB_ARCHIVES_USER < 1) $BACKUP_FILES_MAX_NB_ARCHIVES_USER = "3";
  if ($BACKUP_FILES_MAX_NB_ARCHIVES_USER > 9) $BACKUP_FILES_MAX_NB_ARCHIVES_USER = "9";
  //
  if ( ($LANG != "EN") and ($LANG != "FR") and ($LANG != "IT") and ($LANG != "PT") and ($LANG != "ES") and ($LANG != "BR") and ($LANG != "RO") and ($LANG != "DE") and ($LANG != "NL") ) $LANG = "EN";
  //
  // Corriger les options, et indiquer le nombre (de corrections).
  //
  if ( ($SPECIAL_MODE_OPEN_COMMUNITY != "") and ($SPECIAL_MODE_GROUP_COMMUNITY != "") )
  {
    $SPECIAL_MODE_OPEN_COMMUNITY = "";
    $SPECIAL_MODE_GROUP_COMMUNITY = "";
    $nb_corrections = ($nb_corrections + 2);
    $options_fixed .= "SPECIAL_MODE_OPEN_COMMUNITY#SPECIAL_MODE_GROUP_COMMUNITY#";
  }
  if ( ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY != "") and ($SPECIAL_MODE_GROUP_COMMUNITY != "") ) {$SPECIAL_MODE_OPEN_GROUP_COMMUNITY = ""; $nb_corrections++; $options_fixed .= "SPECIAL_MODE_OPEN_GROUP_COMMUNITY#"; }
  if ( ($SPECIAL_MODE_OPEN_COMMUNITY != "") and ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY != "") ) {$SPECIAL_MODE_OPEN_GROUP_COMMUNITY = ""; $nb_corrections++; $options_fixed .= "SPECIAL_MODE_OPEN_GROUP_COMMUNITY#"; }
  //
  if ( ($CRYPT_MESSAGES != "") and ($HISTORY_MESSAGES_ON_ACP != "") ) {$HISTORY_MESSAGES_ON_ACP = ""; $nb_corrections++; $options_fixed .= "HISTORY_MESSAGES_ON_ACP#"; }
  if ( ($FORCE_UPDATE_BY_INTERNET != "") and ($FORCE_UPDATE_BY_SERVER != "") ) {$FORCE_UPDATE_BY_SERVER = ""; $nb_corrections++; $options_fixed .= "FORCE_UPDATE_BY_SERVER#"; }
  //
  if ($EXTERNAL_AUTHENTICATION != "")
  {
    if ($USER_NEED_PASSWORD == "") {$USER_NEED_PASSWORD = "X"; $nb_corrections++; $options_fixed .= "USER_NEED_PASSWORD#"; }
    if ($ALLOW_AUTO_ADD_NEW_USER_ON_SERVER == "") {$ALLOW_AUTO_ADD_NEW_USER_ON_SERVER = "X"; $nb_corrections++; $options_fixed .= "ALLOW_AUTO_ADD_NEW_USER_ON_SERVER#"; }
    if ($PENDING_NEW_AUTO_ADDED_USER != "") {$PENDING_NEW_AUTO_ADDED_USER = ""; $nb_corrections++; $options_fixed .= "PENDING_NEW_AUTO_ADDED_USER#"; }
    if ($NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER != "") {$NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER = ""; $nb_corrections++; $options_fixed .= "NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER#"; }
  }
  //
  //
  //if ( (strlen($IM_ADDRESS_BOOK_PASSWORD) > 4) and ($ENTERPRISE_SERVER == "") )
  if (strlen($IM_ADDRESS_BOOK_PASSWORD) > 4)
  {
    $nb_corrections_before = $nb_corrections;
    //
    if ($ENTERPRISE_SERVER != "") {$ENTERPRISE_SERVER = ""; $nb_corrections++; $options_fixed .= "ENTERPRISE_SERVER#"; }
    if ($PASSWORD_FOR_PRIVATE_SERVER != "") {$PASSWORD_FOR_PRIVATE_SERVER = ""; $nb_corrections++; $options_fixed .= "PASSWORD_FOR_PRIVATE_SERVER#"; }
    if ($ALLOW_AUTO_ADD_NEW_USER_ON_SERVER == "") {$ALLOW_AUTO_ADD_NEW_USER_ON_SERVER = "X"; $nb_corrections++; $options_fixed .= "ALLOW_AUTO_ADD_NEW_USER_ON_SERVER#"; }
    if ($PENDING_NEW_AUTO_ADDED_USER != "") {$PENDING_NEW_AUTO_ADDED_USER = ""; $nb_corrections++; $options_fixed .= "PENDING_NEW_AUTO_ADDED_USER#"; }
    if ($FORCE_USERNAME_TO_PC_SESSION_NAME != "") {$FORCE_USERNAME_TO_PC_SESSION_NAME = ""; $nb_corrections++; $options_fixed .= "FORCE_USERNAME_TO_PC_SESSION_NAME#"; }
    if ($PENDING_USER_ON_COMPUTER_CHANGE != "") {$PENDING_USER_ON_COMPUTER_CHANGE = ""; $nb_corrections++; $options_fixed .= "PENDING_USER_ON_COMPUTER_CHANGE#"; }
    if ($USER_HIEARCHIC_MANAGEMENT_BY_ADMIN != "") {$USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = ""; $nb_corrections++; $options_fixed .= "USER_HIEARCHIC_MANAGEMENT_BY_ADMIN#"; }
    if ($USER_NEED_PASSWORD == "") {$USER_NEED_PASSWORD = "X"; $nb_corrections++; $options_fixed .= "USER_NEED_PASSWORD#"; }
    if ($HISTORY_MESSAGES_ON_ACP != "") {$HISTORY_MESSAGES_ON_ACP = ""; $nb_corrections++; $options_fixed .= "HISTORY_MESSAGES_ON_ACP#"; }
    if ($CHECK_VERSION_INTERNET == "") {$CHECK_VERSION_INTERNET = "X"; $nb_corrections++; $options_fixed .= "CHECK_VERSION_INTERNET#"; }
    if ($FORCE_UPDATE_BY_SERVER != "") {$FORCE_UPDATE_BY_SERVER = ""; $nb_corrections++; $options_fixed .= "FORCE_UPDATE_BY_SERVER#"; }
    if ($FORCE_UPDATE_BY_INTERNET == "") {$FORCE_UPDATE_BY_INTERNET = "X"; $nb_corrections++; $options_fixed .= "FORCE_UPDATE_BY_INTERNET#"; }
    if ( (intval($MAX_NB_USER) < 200) and (intval($MAX_NB_USER) > 0) ) {$MAX_NB_USER = "0"; $nb_corrections++; $options_fixed .= "MAX_NB_USER#"; }
    if ( (intval($MAX_NB_SESSION) < 50) and (intval($MAX_NB_SESSION) > 0) ) {$MAX_NB_SESSION = "100"; $nb_corrections++; $options_fixed .= "MAX_NB_SESSION#"; }
    //
    if ($nb_corrections > $nb_corrections_before) $ready_for_register_on_server_list = "OK";
  }
  else
  {
    if ($IM_ADDRESS_BOOK_PASSWORD != "") {$IM_ADDRESS_BOOK_PASSWORD = ""; $nb_corrections++; $options_fixed .= "IM_ADDRESS_BOOK_PASSWORD#"; }
  }
  if ($ALLOW_AUTO_ADD_NEW_USER_ON_SERVER == "")
  {
   if ($PENDING_NEW_AUTO_ADDED_USER != "") {$PENDING_NEW_AUTO_ADDED_USER = ""; $nb_corrections++; $options_fixed .= "PENDING_NEW_AUTO_ADDED_USER#"; }
   if ($NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER != "") {$NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER = ""; $nb_corrections++; $options_fixed .= "NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER#"; }
  }
  //if ( ($PENDING_USER_ON_COMPUTER_CHANGE == "") and ($FORCE_USERNAME_TO_PC_SESSION_NAME == "") and ($USER_NEED_PASSWORD == "") ) {$USER_NEED_PASSWORD = "X"; $nb_corrections++; $options_fixed .= "USER_NEED_PASSWORD#"; }
  //if ( ($PENDING_USER_ON_COMPUTER_CHANGE == "") and ($USER_NEED_PASSWORD == "") ) {$USER_NEED_PASSWORD = "X"; $nb_corrections++; $options_fixed .= "USER_NEED_PASSWORD#"; }
  //if ( ($NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER != "") and ($USER_NEED_PASSWORD == "") ) {$USER_NEED_PASSWORD = "X"; $nb_corrections++; $options_fixed .= "USER_NEED_PASSWORD#"; }
  if ( ($CRYPT_MESSAGES != "") and ($HISTORY_MESSAGES_ON_ACP != "") ) {$HISTORY_MESSAGES_ON_ACP = ""; $nb_corrections++; $options_fixed .= "HISTORY_MESSAGES_ON_ACP#"; }
  if ( ($CRYPT_MESSAGES != "") and ($CENSOR_MESSAGES != "") ) {$CENSOR_MESSAGES = ""; $nb_corrections++; $options_fixed .= "CENSOR_MESSAGES#"; }
  if ( ($GROUP_FOR_SBX_AND_ADMIN_MSG != "") and ($SPECIAL_MODE_GROUP_COMMUNITY != "") ) {$GROUP_FOR_SBX_AND_ADMIN_MSG = ""; $nb_corrections++; $options_fixed .= "GROUP_FOR_SBX_AND_ADMIN_MSG#"; }
  if ( ($GROUP_FOR_SBX_AND_ADMIN_MSG != "") and ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY != "") ) {$GROUP_FOR_SBX_AND_ADMIN_MSG = ""; $nb_corrections++; $options_fixed .= "GROUP_FOR_SBX_AND_ADMIN_MSG#"; }
  if ( ($USER_HIEARCHIC_MANAGEMENT_BY_ADMIN != "") and ($SPECIAL_MODE_GROUP_COMMUNITY != "") ) {$USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = ""; $nb_corrections++; $options_fixed .= "USER_HIEARCHIC_MANAGEMENT_BY_ADMIN#"; }
  if ( ($USER_HIEARCHIC_MANAGEMENT_BY_ADMIN != "") and ($SPECIAL_MODE_OPEN_COMMUNITY != "") ) {$USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = ""; $nb_corrections++; $options_fixed .= "USER_HIEARCHIC_MANAGEMENT_BY_ADMIN#"; }
  if ( ($USER_HIEARCHIC_MANAGEMENT_BY_ADMIN != "") and ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY != "") ) {$USER_HIEARCHIC_MANAGEMENT_BY_ADMIN = ""; $nb_corrections++; $options_fixed .= "USER_HIEARCHIC_MANAGEMENT_BY_ADMIN#"; }
  //if ( ($GROUP_USER_CAN_JOIN != "") and ( ($SPECIAL_MODE_GROUP_COMMUNITY == "") or ($GROUP_FOR_SBX_AND_ADMIN_MSG == "") ) ) {$GROUP_USER_CAN_JOIN = ""; $nb_corrections++; $options_fixed .= "GROUP_USER_CAN_JOIN#"; }
  if ( ($GROUP_USER_CAN_JOIN != "") and ($SPECIAL_MODE_GROUP_COMMUNITY == "") and ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY == "") and ($GROUP_FOR_SBX_AND_ADMIN_MSG == "") ) {$GROUP_USER_CAN_JOIN = ""; $nb_corrections++; $options_fixed .= "GROUP_USER_CAN_JOIN#"; }
  if ( ($FLAG_COUNTRY_FROM_IP != "") and ($CHECK_VERSION_INTERNET == "") ) {$CHECK_VERSION_INTERNET = "X";}
  if ( ($SPECIAL_MODE_GROUP_COMMUNITY != "") and ($ALLOW_CONTACT_RATING != "") ) {$ALLOW_CONTACT_RATING = ""; $nb_corrections++; $options_fixed .= "ALLOW_CONTACT_RATING#"; }
  if ( ($SPECIAL_MODE_OPEN_GROUP_COMMUNITY != "") and ($ALLOW_CONTACT_RATING != "") ) {$ALLOW_CONTACT_RATING = ""; $nb_corrections++; $options_fixed .= "ALLOW_CONTACT_RATING#"; }
  if ( ($ROLES_TO_OVERRIDE_PERMISSIONS == "") and ($ROLE_ID_DEFAULT_FOR_NEW_USER > 0) ) {$ROLE_ID_DEFAULT_FOR_NEW_USER = 0; $nb_corrections++; $options_fixed .= "ROLE_ID_DEFAULT_FOR_NEW_USER#"; }
  if ( ($ALLOW_HISTORY_MESSAGES == "") and ($ALLOW_HISTORY_MESSAGES_EXPORT != "") ) {$ALLOW_HISTORY_MESSAGES_EXPORT = ""; $nb_corrections++; $options_fixed .= "ALLOW_HISTORY_MESSAGES_EXPORT#"; }
  //
  if ( ($ALLOW_MANAGE_OPTIONS == "") and ($ALLOW_EMAIL_NOTIFIER != "") ) {$ALLOW_EMAIL_NOTIFIER = ""; $nb_corrections++; $options_fixed .= "ALLOW_EMAIL_NOTIFIER#"; }
  //if ( ($ALLOW_MANAGE_CONTACT_LIST == "") and ($ALLOW_CONTACT_RATING != "") ) {$ALLOW_CONTACT_RATING = ""; $nb_corrections++; $options_fixed .= "ALLOW_CONTACT_RATING#"; }
  
  if ($ALLOW_MANAGE_PROFILE == "")
  {
    //if ($ALLOW_CHANGE_EMAIL_PHONE != "") {$ALLOW_CHANGE_EMAIL_PHONE = ""; $nb_corrections++; $options_fixed .= "ALLOW_CHANGE_EMAIL_PHONE#"; }
    //if ($ALLOW_CHANGE_FUNCTION_NAME != "") {$ALLOW_CHANGE_FUNCTION_NAME = ""; $nb_corrections++; $options_fixed .= "ALLOW_CHANGE_FUNCTION_NAME#"; }
    //if ($ALLOW_CHANGE_AVATAR != "") {$ALLOW_CHANGE_AVATAR = ""; $nb_corrections++; $options_fixed .= "ALLOW_CHANGE_AVATAR#"; }
    //if ($ALLOW_CHANGE_CONTACT_NICKNAME != "") {$ALLOW_CHANGE_CONTACT_NICKNAME = ""; $nb_corrections++; $options_fixed .= "ALLOW_CHANGE_CONTACT_NICKNAME#"; }
    //if ($ALLOW_CONTACT_RATING != "") {$ALLOW_CONTACT_RATING = ""; $nb_corrections++; $options_fixed .= "ALLOW_CONTACT_RATING#"; }
    if ($INVITE_FILL_PROFILE_ON_FIRST_LOGIN != "") {$INVITE_FILL_PROFILE_ON_FIRST_LOGIN = ""; $nb_corrections++; $options_fixed .= "INVITE_FILL_PROFILE_ON_FIRST_LOGIN#"; }
  }
  //
  if ($SHARE_FILES != "")
  {
    //if ( ($SHARE_FILES_NEED_APPROVAL != "") and ($SHARE_FILES_TRASH != "") ) {$SHARE_FILES_TRASH = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES_TRASH#"; }
    //if ( ($SHARE_FILES_EXCHANGE_NEED_APPROVAL != "") and ($SHARE_FILES_EXCHANGE_TRASH != "") ) {$SHARE_FILES_EXCHANGE_TRASH = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES_EXCHANGE_TRASH#"; }
    if ( ($SHARE_FILES_FTP_ADDRESS == "") or ($SHARE_FILES_FTP_LOGIN == "") or ($SHARE_FILES_FTP_PASSWORD_CRYPT == "") ) {$SHARE_FILES = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES (must set FTP parameters!)#"; }
    if ( ($SHARE_FILES_COMPRESS != "") and ( ($SHARE_FILES_NEED_APPROVAL != "") or ($SHARE_FILES_EXCHANGE_NEED_APPROVAL != "") or ($SHARE_FILES_TRASH != "") or ($SHARE_FILES_EXCHANGE_TRASH != "") ) ) {$SHARE_FILES_COMPRESS = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES_COMPRESS#"; }
    if ( ($SHARE_FILES_COMPRESS == "") and ($SHARE_FILES_PROTECT != "") ) {$SHARE_FILES_PROTECT = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES_PROTECT#"; }
  }
  else
  {
    #if ($SHARE_FILES_EXCHANGE != "") {$SHARE_FILES_EXCHANGE = ""; $nb_corrections++; $options_fixed .= "SHARE_FILES_EXCHANGE#"; }
  }
  //
  if ($BACKUP_FILES != "")
  {
    if ( ($BACKUP_FILES_FTP_ADDRESS == "") or ($BACKUP_FILES_FTP_LOGIN == "") or ($BACKUP_FILES_FTP_PASSWORD_CRYPT == "") ) {$BACKUP_FILES = ""; $nb_corrections++; $options_fixed .= "BACKUP_FILES (must set FTP parameters!)#"; }
    if ( ($BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY != "") and ($BACKUP_FILES_ALLOW_MULTI_FOLDERS != "") ) {$BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY = ""; $nb_corrections++; $options_fixed .= "BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY#"; }
    if ( ($BACKUP_FILES_MAX_SPACE_SIZE_USER > 0) and ($BACKUP_FILES_MAX_SPACE_SIZE_TOTAL > 0) and ($BACKUP_FILES_MAX_SPACE_SIZE_USER > $BACKUP_FILES_MAX_SPACE_SIZE_TOTAL) ) {$BACKUP_FILES_MAX_SPACE_SIZE_TOTAL = $BACKUP_FILES_MAX_SPACE_SIZE_USER; $nb_corrections++; $options_fixed .= "BACKUP_FILES_MAX_SPACE_SIZE_TOTAL#"; }
  }
  //
  // ----------------------------
  //        Enregistrement
  // ----------------------------
  //
  if ( (is_writeable("../common/config/config.inc.php")) and ($checkoptionsonly == "") )
  {
    // Backup :
    if (is_writeable("../common/config/config.inc.bak.php")) copy("../common/config/config.inc.php", "../common/config/config.inc.bak.php");
    //
    $fp = fopen("../common/config/config.inc.php", "w"); 
    if (flock($fp, 2)); 
    { 
      //
      fputs($fp, "<?php" . "\r\n"); 
      fputs($fp, "/*******************************************************" . "\r\n"); 
      fputs($fp, " **                  IntraMessenger - server          **" . "\r\n"); 
      fputs($fp, " **                                                   **" . "\r\n"); 
      fputs($fp, " **  Copyright:      (C) 2006 - 2015 THeUDS           **" . "\r\n"); 
      fputs($fp, " **  Web:            http://www.theuds.com            **" . "\r\n"); 
      fputs($fp, " **                  http://www.intramessenger.net    **" . "\r\n"); 
      fputs($fp, " **                  http://www.intramessenger.com    **" . "\r\n"); 
      fputs($fp, " **  Licence:        GPL (GNU Public License)         **" . "\r\n"); 
      fputs($fp, " **  http://opensource.org/licenses/gpl-license.php   **" . "\r\n"); 
      fputs($fp, " *******************************************************/" . "\r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "/*******************************************************" . "\r\n"); 
      fputs($fp, " **       This file is part of IntraMessenger-server  **" . "\r\n"); 
      fputs($fp, " **                                                   **" . "\r\n"); 
      fputs($fp, " **  IntraMessenger is a free software.               **" . "\r\n"); 
      fputs($fp, " **  IntraMessenger is distributed in the hope that   **" . "\r\n"); 
      fputs($fp, " **  it will be useful, but WITHOUT ANY WARRANTY.     **" . "\r\n"); 
      fputs($fp, " *******************************************************/" . "\r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "if ( !defined('INTRAMESSENGER') ) die(); ");
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "define('_LANG', '" . $LANG . "'); \r\n"); 
      fputs($fp, "## EN / FR / IT / PT / BR / RO / DE / ES / NL  \r\n"); 
      fputs($fp, "\r\n"); 
      fputs($fp, "define('_MAINTENANCE_MODE', '" . $MAINTENANCE_MODE . "'); \r\n"); 
      fputs($fp, "## To apply updates (pour effectuer les mises à jour).\r\n"); 
      fputs($fp, "\r\n \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### USERS RESTRICTIONS OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_ALLOW_CONFERENCE', '" . $ALLOW_CONFERENCE . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_HIDDEN_TO_CONTACTS', '" . $ALLOW_HIDDEN_TO_CONTACTS . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_HIDDEN_STATUS', '" . $ALLOW_HIDDEN_STATUS . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_SMILEYS', '" . $ALLOW_SMILEYS . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CHANGE_CONTACT_NICKNAME', '" . $ALLOW_CHANGE_CONTACT_NICKNAME . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CHANGE_EMAIL_PHONE', '" . $ALLOW_CHANGE_EMAIL_PHONE . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CHANGE_FUNCTION_NAME', '" . $ALLOW_CHANGE_FUNCTION_NAME . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CHANGE_AVATAR', '" . $ALLOW_CHANGE_AVATAR . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_UPPERCASE_SPACE_USERNAME', '" . $ALLOW_UPPERCASE_SPACE_USERNAME . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_SEND_TO_OFFLINE_USER', '" . $ALLOW_SEND_TO_OFFLINE_USER . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_HISTORY_MESSAGES', '" . $ALLOW_HISTORY_MESSAGES . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_HISTORY_MESSAGES_EXPORT', '" . $ALLOW_HISTORY_MESSAGES_EXPORT . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_SKIN', '" . $ALLOW_SKIN . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_POST_IT', '" . $ALLOW_POST_IT . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CLOSE_IM', '" . $ALLOW_CLOSE_IM . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_SOUND_USAGE', '" . $ALLOW_SOUND_USAGE . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_REDUCE_MAIN_SCREEN', '" . $ALLOW_REDUCE_MAIN_SCREEN . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_REDUCE_MESSAGE_SCREEN', '" . $ALLOW_REDUCE_MESSAGE_SCREEN . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_CONTACT_RATING', '" . $ALLOW_CONTACT_RATING . "'); \r\n"); 
      fputs($fp, "## If not empty, allow user to rate their contacts (but cannot see average).\r\n"); 
      fputs($fp, "## If 'PUBLIC', users can see their contacts average.\r\n"); 
      fputs($fp, "# \r\n"); 
      fputs($fp, "define('_ALLOW_EMAIL_NOTIFIER', '" . $ALLOW_EMAIL_NOTIFIER . "'); \r\n"); 
      fputs($fp, "define('_INCOMING_EMAIL_SERVER_ADDRESS', '" . $INCOMING_EMAIL_SERVER_ADDRESS . "'); \r\n"); 
      fputs($fp, "define('_INVITE_FILL_PROFILE_ON_FIRST_LOGIN', '" . $INVITE_FILL_PROFILE_ON_FIRST_LOGIN . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_COL_FUNCTION_NAME', '" . $ALLOW_COL_FUNCTION_NAME . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_MANAGE_CONTACT_LIST', '" . $ALLOW_MANAGE_CONTACT_LIST . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_MANAGE_OPTIONS', '" . $ALLOW_MANAGE_OPTIONS . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_MANAGE_PROFILE', '" . $ALLOW_MANAGE_PROFILE . "'); \r\n"); 
      fputs($fp, "define('_FORCE_AWAY_ON_SCREENSAVER', '" . $FORCE_AWAY_ON_SCREENSAVER . "'); \r\n"); 
      fputs($fp, "define('_FORCE_OPTION_FILE_FROM_SERVER', '" . $FORCE_OPTION_FILE_FROM_SERVER . "'); \r\n"); 
      fputs($fp, "define('_FORCE_STATUS_LIST_FROM_SERVER', '" . $FORCE_STATUS_LIST_FROM_SERVER . "'); \r\n"); 
      fputs($fp, "# \r\n"); 
      fputs($fp, "## // example: 'On phone;Meeting;Not in front of screen;Back in 5 minutes;Eating' \r\n"); 
      fputs($fp, "define('_AWAY_REASONS_LIST', " . chr(34) . $AWAY_REASONS_LIST . chr(34) . "); \r\n"); 
      fputs($fp, "define('_ONLINE_REASONS_LIST', " . chr(34) . $ONLINE_REASONS_LIST . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BUSY_REASONS_LIST', " . chr(34) . $BUSY_REASONS_LIST . chr(34) . "); \r\n"); 
      fputs($fp, "define('_DONOTDISTURB_REASONS_LIST', " . chr(34) . $DONOTDISTURB_REASONS_LIST . chr(34) . "); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### SECURITY OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_MINIMUM_USERNAME_LENGTH', '" . $MINIMUM_USERNAME_LENGTH . "'); \r\n"); 
      fputs($fp, "define('_USER_NEED_PASSWORD', '" . $USER_NEED_PASSWORD . "'); \r\n"); 
      fputs($fp, "define('_MINIMUM_PASSWORD_LENGTH', '" . $MINIMUM_PASSWORD_LENGTH . "'); \r\n"); 
      fputs($fp, "define('_PWD_NEED_DIGIT_LETTER', '" . $PWD_NEED_DIGIT_LETTER . "'); \r\n"); 
      fputs($fp, "define('_PWD_NEED_UPPER_LOWER', '" . $PWD_NEED_UPPER_LOWER . "'); \r\n"); 
      fputs($fp, "define('_PWD_NEED_SPECIAL_CHARACTER', '" . $PWD_NEED_SPECIAL_CHARACTER . "'); \r\n"); 
      fputs($fp, "define('_MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER', '" . $MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER . "'); \r\n"); 
      fputs($fp, "define('_LOCK_DURATION', '" . $LOCK_DURATION . "'); \r\n");  // for _MAX_PASSWORD_ERRORS_BEFORE_LOCK_USER
      fputs($fp, "define('_PASSWORD_VALIDITY', '" . $PASSWORD_VALIDITY . "'); \r\n");
      fputs($fp, "define('_CRYPT_MESSAGES', '" . $CRYPT_MESSAGES . "'); \r\n"); 
      fputs($fp, "define('_CENSOR_MESSAGES', '" . $CENSOR_MESSAGES . "'); \r\n"); 
      fputs($fp, "define('_HISTORY_MESSAGES_ON_ACP', '" . $HISTORY_MESSAGES_ON_ACP . "'); \r\n"); 
      fputs($fp, "define('_LOG_SESSION_OPEN', '" . $LOG_SESSION_OPEN . "'); \r\n"); 
      fputs($fp, "define('_FORCE_UPDATE_BY_SERVER', '" . $FORCE_UPDATE_BY_SERVER . "'); \r\n"); 
      fputs($fp, "define('_FORCE_UPDATE_BY_INTERNET', '" . $FORCE_UPDATE_BY_INTERNET . "'); \r\n"); 
      fputs($fp, "define('_SEND_ADMIN_ALERT', '" . $SEND_ADMIN_ALERT . "'); \r\n"); 
      fputs($fp, "define('_UNREAD_MESSAGE_VALIDITY', '" . $UNREAD_MESSAGE_VALIDITY . "'); \r\n"); 
      fputs($fp, "define('_LOCK_AFTER_NO_CONTACT_DURATION', '" . $LOCK_AFTER_NO_CONTACT_DURATION . "'); \r\n"); 
      fputs($fp, "define('_LOCK_AFTER_NO_ACTIVITY_DURATION', '" . $LOCK_AFTER_NO_ACTIVITY_DURATION . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_USE_PROXY', '" . $ALLOW_USE_PROXY . "'); \r\n"); 
      fputs($fp, "define('_PROXY_ADDRESS', '" . $PROXY_ADDRESS . "'); \r\n"); 
      fputs($fp, "define('_PROXY_PORT_NUMBER', '" . $PROXY_PORT_NUMBER . "'); \r\n"); 
      fputs($fp, "define('_PASSWORD_FOR_PRIVATE_SERVER', " . chr(34) . $PASSWORD_FOR_PRIVATE_SERVER . chr(34) . "); \r\n"); 
      fputs($fp, "## Use a long password, to improve security transfert (must be more them 5 characters !).\r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### MAIN OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_SERVERS_STATUS', '" . $SERVERS_STATUS . "'); \r\n"); 
      fputs($fp, "define('_TIME_ZONES', '" . $TIME_ZONES . "'); \r\n"); 
      fputs($fp, "define('_FLAG_COUNTRY_FROM_IP', '" . $FLAG_COUNTRY_FROM_IP . "'); \r\n"); 
      fputs($fp, "define('_GROUP_USER_CAN_JOIN', '" . $GROUP_USER_CAN_JOIN . "'); \r\n"); 
      fputs($fp, "define('_GROUP_FOR_SBX_AND_ADMIN_MSG', '" . $GROUP_FOR_SBX_AND_ADMIN_MSG . "'); \r\n"); 
      fputs($fp, "define('_STATISTICS', '" . $STATISTICS . "'); \r\n"); 
      fputs($fp, "define('_PUBLIC_OPTIONS_LIST', '" . $PUBLIC_OPTIONS_LIST . "'); \r\n"); 
      fputs($fp, "define('_PUBLIC_USERS_LIST', '" . $PUBLIC_USERS_LIST . "'); \r\n"); 
      fputs($fp, "define('_PUBLIC_POST_AVATAR', '" . $PUBLIC_POST_AVATAR . "'); \r\n"); 
      fputs($fp, "define('_PUBLIC_FOLDER', '" . $PUBLIC_FOLDER . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### ADMIN OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_SITE_TITLE', " . chr(34) . $SITE_TITLE . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SITE_URL_TO_SHOW', " . chr(34) . $SITE_URL_TO_SHOW . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SITE_TITLE_TO_SHOW', " . chr(34) . $SITE_TITLE_TO_SHOW . chr(34) . "); \r\n"); 
      //fputs($fp, "## Only a temp message/text :\r\n"); 
      fputs($fp, "define('_SCROLL_TEXT', " . chr(34) . $SCROLL_TEXT . chr(34) . "); \r\n"); 
      fputs($fp, "define('_ADMIN_EMAIL', " . chr(34) . $ADMIN_EMAIL . chr(34) . "); \r\n"); 
      fputs($fp, "define('_ADMIN_PHONE', " . chr(34) . $ADMIN_PHONE . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SEND_ADMIN_ALERT_EMAIL', '" . $SEND_ADMIN_ALERT_EMAIL . "'); \r\n"); 
      fputs($fp, "define('_MAX_NB_USER', '" . $MAX_NB_USER . "'); \r\n"); 
      fputs($fp, "define('_MAX_NB_SESSION', '" . $MAX_NB_SESSION . "'); \r\n"); 
      fputs($fp, "define('_MAX_NB_CONTACT_BY_USER', '" . $MAX_NB_CONTACT_BY_USER . "'); \r\n"); 
      fputs($fp, "define('_MAX_NB_IP', '" . $MAX_NB_IP . "'); \r\n"); 
      fputs($fp, "define('_OUTOFDATE_AFTER_NOT_USE_DURATION', '" . $OUTOFDATE_AFTER_NOT_USE_DURATION . "'); \r\n"); 
      fputs($fp, "define('_CHECK_NEW_MSG_EVERY', '" . $CHECK_NEW_MSG_EVERY . "'); \r\n"); 
      fputs($fp, "define('_SLOW_NOTIFY', '" . $SLOW_NOTIFY . "'); \r\n"); 
      fputs($fp, "define('_CHECK_VERSION_INTERNET', '" . $CHECK_VERSION_INTERNET . "'); \r\n"); 
      fputs($fp, "define('_IM_ADDRESS_BOOK_PASSWORD', '" . $IM_ADDRESS_BOOK_PASSWORD . "'); \r\n"); 
      fputs($fp, "define('_WAIT_STARTUP_IF_SERVER_UNAVAILABLE', '" . $WAIT_STARTUP_IF_SERVER_UNAVAILABLE . "'); \r\n"); 
      fputs($fp, "define('_FORCE_LAUNCH_ON_STARTUP', '" . $FORCE_LAUNCH_ON_STARTUP . "'); \r\n"); 
      fputs($fp, "define('_SKIN_FORCED_COLOR_CUSTOM_VERSION', '" . $SKIN_FORCED_COLOR_CUSTOM_VERSION . "'); \r\n"); 
      fputs($fp, "define('_AUTO_ADD_CONTACT_USER_ID', '" . $AUTO_ADD_CONTACT_USER_ID . "'); \r\n"); 
      fputs($fp, "define('_ROLE_ID_DEFAULT_FOR_NEW_USER', '" . $ROLE_ID_DEFAULT_FOR_NEW_USER . "'); \r\n"); 
      fputs($fp, "define('_GROUP_ID_DEFAULT_FOR_NEW_USER', '" . $GROUP_ID_DEFAULT_FOR_NEW_USER . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### SPECIALS OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_ACP_PROTECT_BY_HTACCESS', '" . $ACP_PROTECT_BY_HTACCESS . "'); \r\n"); 
      fputs($fp, "define('_ACP_ALLOW_MEMORY_AUTH', '" . $ACP_ALLOW_MEMORY_AUTH . "'); \r\n"); 
      fputs($fp, "define('_SPECIAL_MODE_OPEN_COMMUNITY', '" . $SPECIAL_MODE_OPEN_COMMUNITY . "'); \r\n"); 
      fputs($fp, "define('_SPECIAL_MODE_GROUP_COMMUNITY', '" . $SPECIAL_MODE_GROUP_COMMUNITY . "'); \r\n"); 
      fputs($fp, "define('_SPECIAL_MODE_OPEN_GROUP_COMMUNITY', '" . $SPECIAL_MODE_OPEN_GROUP_COMMUNITY . "'); \r\n"); 
      fputs($fp, "define('_ROLES_TO_OVERRIDE_PERMISSIONS', '" . $ROLES_TO_OVERRIDE_PERMISSIONS . "'); \r\n"); 
      fputs($fp, "define('_ENTERPRISE_SERVER', '" . $ENTERPRISE_SERVER . "'); \r\n"); 
      fputs($fp, "define('_FORCE_USERNAME_TO_PC_SESSION_NAME', '" . $FORCE_USERNAME_TO_PC_SESSION_NAME . "'); \r\n"); 
      fputs($fp, "define('_ALLOW_AUTO_ADD_NEW_USER_ON_SERVER', '" . $ALLOW_AUTO_ADD_NEW_USER_ON_SERVER . "'); \r\n"); 
      fputs($fp, "define('_NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER', '" . $NEED_QUICK_REGISTER_TO_AUTO_ADD_NEW_USER . "'); \r\n"); 
      fputs($fp, "define('_PENDING_NEW_AUTO_ADDED_USER', '" . $PENDING_NEW_AUTO_ADDED_USER . "'); \r\n"); 
      fputs($fp, "define('_PENDING_USER_ON_COMPUTER_CHANGE', '" . $PENDING_USER_ON_COMPUTER_CHANGE . "'); \r\n"); 
      fputs($fp, "define('_USER_HIEARCHIC_MANAGEMENT_BY_ADMIN', '" . $USER_HIEARCHIC_MANAGEMENT_BY_ADMIN . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### BOOKMARKS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_BOOKMARKS', '" . $BOOKMARKS . "'); \r\n"); 
      fputs($fp, "define('_BOOKMARKS_VOTE', '" . $BOOKMARKS_VOTE . "'); \r\n"); 
      fputs($fp, "define('_BOOKMARKS_PUBLIC', '" . $BOOKMARKS_PUBLIC . "'); \r\n"); 
      fputs($fp, "define('_BOOKMARKS_NEED_APPROVAL', '" . $BOOKMARKS_NEED_APPROVAL . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### SHOUTBOX ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_SHOUTBOX', '" . $SHOUTBOX . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_REFRESH_DELAY', '" . $SHOUTBOX_REFRESH_DELAY . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_STORE_DAYS', '" . $SHOUTBOX_STORE_DAYS . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_STORE_MAX', '" . $SHOUTBOX_STORE_MAX . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_QUOTA_USER_DAY', '" . $SHOUTBOX_QUOTA_USER_DAY . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_QUOTA_USER_WEEK', '" . $SHOUTBOX_QUOTA_USER_WEEK . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_NEED_APPROVAL', '" . $SHOUTBOX_NEED_APPROVAL . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_APPROVAL_QUEUE_USER', '" . $SHOUTBOX_APPROVAL_QUEUE_USER . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_APPROVAL_QUEUE', '" . $SHOUTBOX_APPROVAL_QUEUE . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_LOCK_USER_APPROVAL', '" . $SHOUTBOX_LOCK_USER_APPROVAL . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_VOTE', '" . $SHOUTBOX_VOTE . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_MAX_NOTES_USER_DAY', '" . $SHOUTBOX_MAX_NOTES_USER_DAY . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_MAX_NOTES_USER_WEEK', '" . $SHOUTBOX_MAX_NOTES_USER_WEEK . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_REMOVE_MESSAGE_VOTES', '" . $SHOUTBOX_REMOVE_MESSAGE_VOTES . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_LOCK_USER_VOTES', '" . $SHOUTBOX_LOCK_USER_VOTES . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_ALLOW_SCROLLING', '" . $SHOUTBOX_ALLOW_SCROLLING . "'); \r\n"); 
      fputs($fp, "define('_SHOUTBOX_PUBLIC', '" . $SHOUTBOX_PUBLIC . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### SHARE FILES ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_SHARE_FILES', '" . $SHARE_FILES . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE', '" . $SHARE_FILES_EXCHANGE . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FOLDER', " . chr(34) . $SHARE_FILES_FOLDER . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FTP_ADDRESS', " . chr(34) . $SHARE_FILES_FTP_ADDRESS . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FTP_LOGIN', " . chr(34) . $SHARE_FILES_FTP_LOGIN . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FTP_PASSWORD', " . chr(34) . $SHARE_FILES_FTP_PASSWORD . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FTP_PASSWORD_CRYPT', " . chr(34) . $SHARE_FILES_FTP_PASSWORD_CRYPT . chr(34) . "); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_FTP_PORT_NUMBER', '" . $SHARE_FILES_FTP_PORT_NUMBER . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_MAX_FILE_SIZE', '" . $SHARE_FILES_MAX_FILE_SIZE . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_MAX_NB_FILES_TOTAL', '" . $SHARE_FILES_MAX_NB_FILES_TOTAL . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_MAX_NB_FILES_USER', '" . $SHARE_FILES_MAX_NB_FILES_USER . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_MAX_SPACE_SIZE_TOTAL', '" . $SHARE_FILES_MAX_SPACE_SIZE_TOTAL . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_MAX_SPACE_SIZE_USER', '" . $SHARE_FILES_MAX_SPACE_SIZE_USER . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_NEED_APPROVAL', '" . $SHARE_FILES_NEED_APPROVAL . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE_NEED_APPROVAL', '" . $SHARE_FILES_EXCHANGE_NEED_APPROVAL . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_APPROVAL_QUEUE', '" . $SHARE_FILES_APPROVAL_QUEUE . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_QUOTA_FILES_USER_WEEK', '" . $SHARE_FILES_QUOTA_FILES_USER_WEEK . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_ALLOW_UPPERCASE', '" . $SHARE_FILES_ALLOW_UPPERCASE . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_ALLOW_ACCENT', '" . $SHARE_FILES_ALLOW_ACCENT . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_VOTE', '" . $SHARE_FILES_VOTE . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_TRASH', '" . $SHARE_FILES_TRASH . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE_TRASH', '" . $SHARE_FILES_EXCHANGE_TRASH . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE_UNREAD_VALIDITY', '" . $SHARE_FILES_EXCHANGE_UNREAD_VALIDITY . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_SCREENSHOT', '" . $SHARE_FILES_SCREENSHOT . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE_SCREENSHOT', '" . $SHARE_FILES_EXCHANGE_SCREENSHOT . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_WEBCAM', '" . $SHARE_FILES_WEBCAM . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_EXCHANGE_WEBCAM', '" . $SHARE_FILES_EXCHANGE_WEBCAM . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_COMPRESS', '" . $SHARE_FILES_COMPRESS . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_PROTECT', '" . $SHARE_FILES_PROTECT . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_DAY', '" . $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_DAY . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_WEEK', '" . $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_WEEK . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_MONTH', '" . $SHARE_FILES_DOWNLOAD_QUOTA_FILES_USER_MONTH . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_DAY', '" . $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_DAY . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_WEEK', '" . $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_WEEK . "'); \r\n"); 
      fputs($fp, "define('_SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_MONTH', '" . $SHARE_FILES_DOWNLOAD_QUOTA_MB_USER_MONTH . "'); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### BACKUP FILES ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_BACKUP_FILES', '" . $BACKUP_FILES . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_MAX_NB_ARCHIVES_USER', '" . $BACKUP_FILES_MAX_NB_ARCHIVES_USER . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_MAX_ARCHIVE_SIZE', '" . $BACKUP_FILES_MAX_ARCHIVE_SIZE . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_MAX_SPACE_SIZE_USER', '" . $BACKUP_FILES_MAX_SPACE_SIZE_USER . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_MAX_SPACE_SIZE_TOTAL', '" . $BACKUP_FILES_MAX_SPACE_SIZE_TOTAL . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY', " . chr(34) . $BACKUP_FILES_THIS_LOCAL_FOLDER_ONLY . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FORCE_EVERY_DAY_AT', '" . $BACKUP_FILES_FORCE_EVERY_DAY_AT . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_ALLOW_MULTI_FOLDERS', '" . $BACKUP_FILES_ALLOW_MULTI_FOLDERS . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_ALLOW_SUB_FOLDERS', '" . $BACKUP_FILES_ALLOW_SUB_FOLDERS . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FTP_ADDRESS', " . chr(34) . $BACKUP_FILES_FTP_ADDRESS . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FTP_LOGIN', " . chr(34) . $BACKUP_FILES_FTP_LOGIN . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FTP_PASSWORD', " . chr(34) . $BACKUP_FILES_FTP_PASSWORD . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FTP_PASSWORD_CRYPT', " . chr(34) . $BACKUP_FILES_FTP_PASSWORD_CRYPT . chr(34) . "); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FTP_PORT_NUMBER', '" . $BACKUP_FILES_FTP_PORT_NUMBER . "'); \r\n"); 
      fputs($fp, "define('_BACKUP_FILES_FOLDER', " . chr(34) . $BACKUP_FILES_FOLDER . chr(34) . "); \r\n"); 
      fputs($fp, "\r\n# \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "###################################### EXTERNAL AUTHENTICATION OPTIONS ###################################### \r\n"); 
      fputs($fp, "## \r\n"); 
      fputs($fp, "# \r\n \r\n"); 
      fputs($fp, "define('_EXTERNAL_AUTHENTICATION', '" . $EXTERNAL_AUTHENTICATION . "'); \r\n"); 
      fputs($fp, "define('_EXTERN_URL_TO_REGISTER', " . chr(34) . $EXTERN_URL_TO_REGISTER . chr(34) . "); \r\n"); 
      fputs($fp, "define('_EXTERN_URL_FORGET_PASSWORD', " . chr(34) . $EXTERN_URL_FORGET_PASSWORD . chr(34) . "); \r\n"); 
      fputs($fp, "define('_EXTERN_URL_CHANGE_PASSWORD', " . chr(34) . $EXTERN_URL_CHANGE_PASSWORD . chr(34) . "); \r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "## Server change is public:\r\n"); 
      fputs($fp, "define('_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL', " . chr(34) . $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL . chr(34) . "); \r\n"); 
      fputs($fp, "## Only for authenticated users:\r\n"); 
      fputs($fp, "define('_STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN', " . chr(34) . $STOP_USE_THIS_SERVER_ADDRESS_NOW_USE_THIS_URL_AFTER_LOGIN . chr(34) . "); \r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "# Server version: " . _SERVER_VERSION . "\r\n"); 
      fputs($fp, "# Options date: " . date("Y-m-d") . "\r\n"); 
      //
      fputs($fp, "" . "\r\n"); 
      fputs($fp, "?>"); 
      flock($fp, 3); 
    } 
    fclose($fp); 
  }
}
//
//if ( ($step > 0) and ($lic == "ok") ) // bug
if ($step > 0)
  header("location:../install/install.php?lang=" . $lang . "&step=" . $step . "&lic=" . $lic . "&");
else
{
  require("../common/log.inc.php");
  write_log("log_options_update", $nb_corrections . ";" . $options_fixed . ";");
  //
  if ($check == "update")
    header("location:check.php?lang=" . $lang . "&");
  else
  {
    //if ( ($ready_for_register_on_server_list == "OK") and ($checkoptionsonly == "") )
    //  header("location:register_to_public_servers_list.php?lang=" . $lang . "&");
    //else
      header("location:list_options_updating.php?lang=" . $lang . "&nb_corr=" . $nb_corrections . "&list_corr=" . base64_encode($options_fixed) . "&");
  }
}
?>